### ISSUE TITLE
希望TagUI 增加这个中文OCR支持 - https://github.com/DayBreak-u/chineseocr_lite

### ISSUE THREAD

**Issue by kangyiwen** [aisingapore/TagUI#1245]
Hi  目前TagUI识别中文不太好用，我找了个开源中文OCR，希望在以后的 TagUI 版本里，可以融入这个，请考虑下。

https://github.com/DayBreak-u/chineseocr_lite

**Comment by twinyk** [comment]
这话说的，好像英文识别也好用似的。。。哈哈哈
















在 2022-06-17 23:26:15，"kangyiwen" ***@***.***> 写道：

Hi 目前TagUI识别中文不太好用，我找了个开源中文OCR，希望在以后的 TagUI 版本里，可以融入这个，请考虑下。

https://github.com/DayBreak-u/chineseocr_lite

**Comment by ruthtxh** [comment]
Hi @kangyiwen, thanks for the suggestion we will keep this in view.
