### ISSUE TITLE
New feature and dedicated PrivateBin server for RPA for Python - for reviewing

### ISSUE THREAD

**Issue by kensoh** [aisingapore/TagUI#1250]
Hi @ruthtxh I've recently created a new instance of PrivateBin to let RPA for Python users securely share content like file attachments from RPA workflows. See below for more info, I implemented a bin() function to do the automate through web frontend, so that there is no dependency on other packages which in turn has other dependencies.

Fyi in case this is a feature you want to add into TagUI. Offhand, I think the easiest is a workflow .tag file which users can call from tagui step. It is probably hard to make it an in-built function in TagUI without unexpected side effects, as TagUI JavaScript code is generated from the .tag file of steps.

**Usage examples (can be used through bin() or PrivateBin API Python package)**
- https://github.com/tebelorg/RPA-Python/issues/396#issuecomment-1169409452

**PrivateBin instance (I've improved the server security to A+ on Mozilla web security)**
- Instance URL, configured to support files max 10MB max 1 week - https://tebel.org/bin/
- List of instances showing A+ for this instance - https://privatebin.info/directory/

**Logic of bin() which can be mapped to equivalent TagUI steps to achieve the same effect**
- https://github.com/tebelorg/RPA-Python/commit/a0f5b5d7411173b9b8b1b3a7573108f996abfee1

**Comment by ruthtxh** [comment]
Hi @kensoh 

Thanks for sharing this, I will check this out!

**Comment by kensoh** [comment]
Sure, let me know if you run into any questions! PrivateBin can be easily hosted too on your own, if you want to host it on AI Singapore's servers. It just needs basic LAMP (Linux + Apache + MySQL + PHP) stack to run. MySQL not sure if it uses.

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant or an issue.
