### ISSUE TITLE
Chrome Web Store EU Trader/Non-Trader developer identification - republished

### ISSUE THREAD

**Issue by kensoh** [aisingapore/TagUI#1252]
Hi @ruthtxh I was checking latest user geographical distribution for TagUI Chrome extension ([to update user distribution map](https://github.com/kensoh/tagui_distribution)), and I saw a prompt asking me if I'm a trader or non-trader. [See the definition here](https://developer.chrome.com/docs/webstore/trader-disclosure/). This looks like an EU prompt for EU consumer protection. I chose non-trader because it will ask me for a business address which is obviously invalid for me.

Raising an issue here so that you can try out and see if you want to update the Chrome extension account settings as trader. It will require entering AI Singapore's business address. The pro of updating I believe is it will not prompt EU users of something like below, base on the definition link above.

>If you are a non-trader, the consumer will be informed that consumer rights stemming from consumer protection laws may not apply to any contracts between you and the consumer. Please note that it is the developer’s responsibility to accurately self-declare their trader/non-trader status.

The link to the Chrome extension developer console is https://chrome.google.com/webstore/devconsole and it is under AI Singapore group publisher account at tagui-rpa@googlegroups.com which I believe you and Najib are already inside.

**Comment by kensoh** [comment]
Want to add that I'm not recommending to choose trader or non-trader, but wants to highlight that there is such a thing for EU market. And you guys can weigh whether to choose either, or just ignore since if there's a problem users would feedback by now.

**Comment by ruthtxh** [comment]
Hi @kensoh noted on the trader account issue, we are looking into this.
We are also looking into the possibility of changing the group publisher account to an internal group instead of the current external group (tagui-rpa@googlegroups.com), I will let you know if I require any information from you. Thanks!

**Comment by kensoh** [comment]
Sure! Let me know if any info or action required from my side :)

**Comment by ruthtxh** [comment]
Hi @kensoh , we are republishing the chrome extension with a new publisher account that is tied to AISG instead and as such we will track the downloads from the new source. Will link it up when it is ready, thanks!

**Comment by kensoh** [comment]
Oh I see, the tagui-rpa@googlegroups.com is already tied to AISG and is created by Najib. I assume you meant that there is a new one that maybe ends with @aisingapore.org. I got the following email from Google saying that the app will be deleted.

Fyi, to see if you would want to publish the new extension first successfully, before deleting the old one, and finally mapping all links to the new one. Otherwise there may be a gap between deleting and the new one being available. I haven't publish for a long time so there may be new requirements including changing some parts of the code base / config for an app to be able to be published.

---

Hi there,

We've received your request to permanently delete the group publisher account [tagui-rpa@googlegroups.com](mailto:tagui-rpa@googlegroups.com).

As part of the deletion process, all extensions, themes and apps associated with this group publisher will also be permanently deleted.

You can learn more about group publisher deletion [here](https://developer.chrome.com/webstore/account-deletion).


Sincerely,

Chrome Web Store Developer Support

**Comment by ruthtxh** [comment]
@kensoh I see, I have already feedback to Najib about the group publisher. I've updated the link to the new extension [here](https://chrome.google.com/webstore/detail/tagui-rpa-web-recorder/gjdajlcpkkjgjjokkekiniengajiamnk/) and yes some codes had to be change to suit the new manifest format as well as the api, will update the backup source code on github soon.

**Comment by kensoh** [comment]
Oh @ruthtxh nice republishing the extension, making it compliant and all the styling touches!

Since I've known you, you have been great at tackling on new challenges and tools. Thumbs up 👍🏻👍🏻

**Comment by gordicaleksa** [comment]
Hey does this mean that if we have a non-trader account and we publish an extension under it, we can't post-hoc swap the account to a trader account?

And will thus lose all of our userbase if we decide to switch? Am I understanding this correctly?

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant or an issue.
