### ISSUE TITLE
Excel Step string of numbers with leading 0 outputs as number without leading 0 - fixed

### ISSUE THREAD

**Issue by ruthtxh** [aisingapore/TagUI#1254]
Source: Telegram group chat (https://t.me/rpa_chat/14086)

**Comment by kensoh** [comment]
Hi @ruthtxh I've closed the feature / bug issues which are in latest packaged release. For this issue, if you close, it will not show up in the following link (from docs installation page) - 

https://github.com/kelaberetiv/TagUI/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+fixed+OR+done+

**Comment by ruthtxh** [comment]
Reopening issue for visibility till next release due to above [reason](https://github.com/kelaberetiv/TagUI/issues/1255#issuecomment-1185286121).

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant or an issue.
