### ISSUE TITLE
Error when copy excel data with empty array values to other workbook - fixed

### ISSUE THREAD

**Issue by Dj0672** [aisingapore/TagUI#1255]
Hi Ruth,

I have data range in Excel from A3:D9 which content value. If I try to copy from A3:D10 (all data in row 10 is empty) to other workbook, Tagui will throw en error : undefined is not an object (evaluating 'excel_result[row][col].toString'). Please kindly check.

Thanks.

**Comment by ruthtxh** [comment]
Hi @Dj0672 

I tried to replicate your error but was unable to.

Can you provide more information so we can look into it?
1. What version of TagUI are you running on? You can do so by running `tagui` in the command prompt/terminal.
2. What OS are you on?
3. Can you share more information on a small sample dataset, TagUI script, and automation output... similar to the one I have attached below. Thanks!
![image](https://user-images.githubusercontent.com/40910744/178642389-ec436f59-d1a8-424b-b8c6-c2b8b4fe416d.png)

![image](https://user-images.githubusercontent.com/40910744/178642321-09a58ae7-4801-4938-b3cc-0ad14138726c.png)

![image](https://user-images.githubusercontent.com/40910744/178642294-89812aba-d54a-4160-b5ee-bbce2fadcf41.png)

**Comment by ruthtxh** [comment]
@Dj0672 I have added the fix for the above, can you update TagUI by running the following command `tagui update` and let me know if there's any issues?

**Comment by Dj0672** [comment]
Thanks Ruth. It is working now.

**Comment by kensoh** [comment]
Hi @ruthtxh I've closed the feature / bug issues which are in latest packaged release. For this issue, if you close, it will not show up in the following link (from docs installation page) -

https://github.com/kelaberetiv/TagUI/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+fixed+OR+done+

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant or an issue.
