### ISSUE TITLE
How to get popup answer - some tips

### ISSUE THREAD

**Issue by MaheshPMane** [aisingapore/TagUI#1256]
Hi
Pl. Check below code and guide

vision output_sikuli_text(popAsk('Exit'))
input_result = fetch_sikuli_text()

Flow gets hang while executing last command.

**Comment by marcelocecin** [comment]
https://github.com/kelaberetiv/TagUI/issues/908

**Comment by ruthtxh** [comment]
Hi @MaheshPMane 
You can use the vairable `ask_result`
For more information check out the docs [here](https://tagui.readthedocs.io/en/latest/reference.html#ask).

**Comment by kensoh** [comment]
Adding on, @MaheshPMane if what you are looking for is doing a popup on the desktop instead of web-browser, the link that @marcelocecin sent would be a working example. @ruthtxh would be one for asking a popup on the browser.

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant or an issue.
