### ISSUE TITLE
cannot  find  element ,use type  [html path] 

### ISSUE THREAD

**Issue by cousin-wang** [aisingapore/TagUI#1263]
https://mail.qq.com/  

Please look at the picture.

<img width="519" alt="C5E83A14-EAC9-4a10-8735-4FE9E7F9229F" src="https://user-images.githubusercontent.com/60058463/181143172-bd7519bd-e0df-479a-8961-c0f9e2855cb8.png">
<img width="518" alt="lQLPJxaIpOOFRs3M9c0EC7Dsc1rvG1eRiALg8amAQCwA_1035_245" src="https://user-images.githubusercontent.com/60058463/181143176-556723b5-9c0a-49db-a183-0d7daf3f5a52.png">

**Comment by ruthtxh** [comment]
Hi @cousin-wang 

in that case you can read the src of the iframe and access it directly to login. For example:
```
http://mail.qq.com/
read //*[@id="login_frame"]/@src to url
https://`url.replace("https://", "")`
click //*[@id="switcher_plogin"]
type //*[@id="u"] as xyz
type //*[@id="p"] as bbb
click //*[@id="login_button"]
```

**Comment by cousin-wang** [comment]
thank you, your example   can be used

Why doesn't using lable( Frame) work ? As I write   
@ruthtxh

**Comment by marcelocecin** [comment]
```
http://mail.qq.com/
wait
keyboard [tab]user[tab]
keyboard pass[enter]
```

**Comment by kensoh** [comment]
@cousin-wang, if you adapt @ruthtxh working code and combine with using frame step, does it work for you?

```
http://mail.qq.com/
frame login_frame
    click //*[@id="switcher_plogin"]
    type //*[@id="u"] as xyz
    type //*[@id="p"] as bbb
    click //*[@id="login_button"]
```

But yeah, if you are ok with visual automation, @marcelocecin's solution will be easiest to implement and understand.
