### ISSUE TITLE
run TagUI with -h , error 

### ISSUE THREAD

**Issue by cenwenchu** [aisingapore/TagUI#1264]
error msg as below:

click //*[@id="fxg-pc-header"]/div[1]/div[1]/div/div[2]/div[2]/div/div[2]/div
ERROR - cannot find //*[@id="fxg-pc-header"]/div[1]/div[1]/div/div[2]/div[2]/div/div[2]/div
/usr/local/bin/tagui: line 459:  1420 Terminated: 15          "$tagui_browser_command" --user-data-dir="$TAGUI_DIR/chrome/tagui_user_profile" $chrome_switches $window_size $headless_switch $no_sandbox_switch > /dev/null 2>&1

-----------------------------------

if run as TagUI -h , not support click XPATH?

**Comment by ruthtxh** [comment]
Hi @cenwenchu could it be that the page is rendered differently in headless mode such that the xpath cannot be found?

You can try this suggestion [here](https://github.com/kelaberetiv/TagUI/issues/919#issuecomment-768766255) to check the html of the headless page.

**Comment by kensoh** [comment]
Adding on, if it is necessary to run in headless mode but hard to figure out the XPaths, you can try out solutions like Xvfb to create virtual frame buffer display. And run Chrome in the normal visible mode. That should render the webpage accurately.

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant or an issue.
