### ISSUE TITLE
HTTP / HTTPS / SOCKS Proxy for Chrome/Edge

### ISSUE THREAD

**Issue by austin-millan** [aisingapore/TagUI#1266]
# About

I understand from your workaround comment posted [here](https://github.com/kelaberetiv/TagUI/issues/162#issuecomment-516743499) that you are not interested in enabling "special chrome options" besides what's necessary for RPA.

Yet there are a number of users (myself included) where proxying requests are a necessary step in automation of browsers:
- https://github.com/kelaberetiv/TagUI/issues/162
- https://github.com/kelaberetiv/TagUI/issues/1124
- https://github.com/kelaberetiv/TagUI/issues/1193
- https://github.com/tebelorg/RPA-Python/issues/395
- https://github.com/tebelorg/RPA-Python/issues/377
- https://github.com/tebelorg/RPA-Python/issues/312
- https://github.com/tebelorg/RPA-Python/issues/97

I believe the only workaround for this use-case is what you've already shared (make changes within this codebase), but editing source code directly may not be feasible for all situations.

Would you consider a PR that would enable this use-case or is there no interest here?

**Comment by ruthtxh** [comment]
Hi @austin-millan thanks for raising this, our team has reviewed internally and there's no plans to include this feature at the moment due to the following reasons:
1) low impact to majority of user base
2) there are easy to implement workarounds

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant or an issue.

**Comment by austin-millan** [comment]
@kensoh , I dropped my use of RPA-python 2 years ago due to the lack of support for my request. So for me it is no longer an issue.

**Comment by kensoh** [comment]
Thanks @austin-millan for your reply!
