### ISSUE TITLE
dom in the iframe steps

### ISSUE THREAD

**Issue by limengtaylor** [aisingapore/TagUI#1270]
![image](https://user-images.githubusercontent.com/36980796/182567113-8bc16235-6c29-4284-9473-8604b13187dd.png)
dom in the iframe steps,in fact ,the scope  is the outer document no in the iframe

**Comment by ruthtxh** [comment]
Hi @limengtaylor you can identify the iframe element first, then find the element you want. There is an example [here](https://www.w3schools.com/howto/howto_js_element_iframe.asp)

**Comment by limengtaylor** [comment]
> Hi @limengtaylor you can identify the iframe element first, then find the element you want. There is an example [here](https://www.w3schools.com/howto/howto_js_element_iframe.asp)

Thanks you,i have find the element,but when the iframe has father iframe and grandfather iframe,the way to get element will be complicated,like this picture
![image](https://user-images.githubusercontent.com/36980796/182985660-bf282834-81b0-4d81-9e14-0f291355faae.png)

**Comment by ruthtxh** [comment]
Hi @limengtaylor we can continue the discussion of 3 iframes in this thread https://github.com/kelaberetiv/TagUI/issues/1272!

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant or an issue.
