### ISSUE TITLE
how to use three iframe 

### ISSUE THREAD

**Issue by limengtaylor** [aisingapore/TagUI#1272]
![image](https://user-images.githubusercontent.com/36980796/182807600-0afb8c13-c88c-4c27-a579-b0dad69d9320.png)
when the web have 3 or more iframe ,how to get the dom to use click,hover,upload;

**Comment by ruthtxh** [comment]
Hi @limengtaylor what is the error message you're getting? Are you able to share the website so we can take a look please?

**Comment by limengtaylor** [comment]
![image](https://user-images.githubusercontent.com/36980796/182982259-6930f978-d9b1-49c0-b8b7-2096f0f07b97.png)
The picture is the error message;
the element in the third iframe can't be finded;
Th the function Chrome.withFrame,there are mainframe_context and subframe_context,if the webpage hava the iframe more 2 level，how to click the elements?
![image](https://user-images.githubusercontent.com/36980796/182982634-33fe9327-81c3-45f4-b619-033a807cf5cd.png)



> Hi @limengtaylor what is the error message you're getting? Are you able to share the website so we can take a look please?

![image](https://user-images.githubusercontent.com/36980796/182983493-b2327cca-d34f-491d-9bb5-ab93c43031d4.png)
The picture is the error message;
the element in the third iframe can't be finded;
Th the function Chrome.withFrame,there are mainframe_context and subframe_context,if the webpage hava the iframe more 2 level，how to click the elements?
![image](https://user-images.githubusercontent.com/36980796/182983552-8a8bbbd3-72ed-4faf-ad48-99ff7c1199da.png)

**Comment by ruthtxh** [comment]
Hi @limengtaylor currently there is only support for 2 layers of iframes, can you share your website so we can see if there is a workaround for your scenario?

You can try [this](https://github.com/kelaberetiv/TagUI/issues/1129#issuecomment-966355165) and see if it works for you,  by accessing the first iframe via the url directly.

**Comment by limengtaylor** [comment]
> Hi @limengtaylor currently there is only support for 2 layers of iframes, can you share your website so we can see if there is a workaround for your scenario?
> 
> You can try [this](https://github.com/kelaberetiv/TagUI/issues/1129#issuecomment-966355165) and see if it works for you, by accessing the first iframe via the url directly.

I use 'dom'  made a three iframes tag,and how  to solve more than 3 iframes,4 iframes ,5 iframes,some old Intranet there are so many iframes.
https://www.antdv.com/components/button
wait 5
dom begin
var dom1 = document.querySelector('#header');
var frame1 = document.createElement("iframe");
frame1.setAttribute('id','mainFrame');
frame1.setAttribute('src','https://www.antdv.com/docs/vue/introduce-cn');
frame1.style.width='1100px';
frame1.style.height='1200px';
frame1.style.display='block';
dom1.append(frame1);
dom finish
wait 10
dom begin
console.log('dom2',document.getElementsByTagName("iframe")['mainFrame'].contentDocument)
var dom2 = document.getElementsByTagName("iframe")['mainFrame'].contentDocument.querySelector('#header');
var frame2 = document.createElement("iframe");
frame2.setAttribute('id','subFrame');
frame2.setAttribute('src','https://www.antdv.com/components/overview-cn/');
frame2.style.width='900px';
frame2.style.height='1000px';
frame2.style.display='block';
dom2.append(frame2);
dom finish
wait 10
dom begin
var dom3 = document.getElementsByTagName("iframe")['mainFrame'].contentDocument.getElementsByTagName("iframe")['subFrame'].contentDocument.querySelector('#app > div > div > div > section.main-container > section > div:nth-child(6) > h2');
var iframe3 = document.createElement("iframe");
iframe3.setAttribute('id','sunFrame');
iframe3.setAttribute('src','https://www.antdv.com/components/table-cn');
iframe3.style.width='700px';
iframe3.style.height='700px';
iframe3.style.display='block';
dom3.append(iframe3);
dom finish
wait 10
frame mainFrame
   frame subFrame
      frame sunFrame
         dom console.log(document.getElementsByTagName("iframe")['mainFrame'].contentDocument.getElementsByTagName("iframe")['subFrame'].contentDocument.getElementsByTagName("iframe")['sunFrame'].contentDocument.querySelector('body > div.drawer-wrapper > div > div.ant-drawer-content-wrapper > div:nth-child(2) > div > span > svg'))
         click body > div.drawer-wrapper > div > div.ant-drawer-content-wrapper > div:nth-child(2) > div > span > svg
wait 50
