### ISSUE TITLE
snap (0,0)-(100,100) to snap.png  can't get snap.tag - install OpenJDK and reinstall TagUI

### ISSUE THREAD

**Issue by limengtaylor** [aisingapore/TagUI#1273]
![image](https://user-images.githubusercontent.com/36980796/183802654-42a066f4-5536-4541-b1a8-db54914f4f54.png)
![image](https://user-images.githubusercontent.com/36980796/183802690-0aad39e8-0230-46cf-8cbf-eafd92ed5fef.png)
![image](https://user-images.githubusercontent.com/36980796/183802781-e0292ad6-10fd-4156-9d36-56d1e03de685.png)

**Comment by ruthtxh** [comment]
Hi @limengtaylor can you share the tagui log in tagui\src\tagui.sikuli? It should look something like this:
![image](https://user-images.githubusercontent.com/40910744/184055386-5ec3a54a-6ea4-4154-9f13-b406214b1517.png)

**Comment by limengtaylor** [comment]
the log is null

> Hi @limengtaylor can you share the tagui log in tagui\src\tagui.sikuli? It should look something like this: ![image](https://user-images.githubusercontent.com/40910744/184055386-5ec3a54a-6ea4-4154-9f13-b406214b1517.png)

the log is null,i don't know the reason;

**Comment by lookang** [comment]
I helped my colleague before on this issue, his reason is didn't install java
https://tagui.readthedocs.io/en/latest/setup.html
[Install OpenJDK for Windows](https://corretto.aws/downloads/latest/amazon-corretto-8-x64-windows-jdk.msi)

**Comment by limengtaylor** [comment]
> Hi @limengtaylor can you share the tagui log in tagui\src\tagui.sikuli? It should look something like this: ![image](https://user-images.githubusercontent.com/40910744/184055386-5ec3a54a-6ea4-4154-9f13-b406214b1517.png)

after install OpenJDK，
![image](https://user-images.githubusercontent.com/36980796/184274936-ca2a5e33-f8a6-4793-aa7a-2f591648666c.png)

**Comment by limengtaylor** [comment]
> I helped my colleague before on this issue, his reason is didn't install java https://tagui.readthedocs.io/en/latest/setup.html [Install OpenJDK for Windows](https://corretto.aws/downloads/latest/amazon-corretto-8-x64-windows-jdk.msi)

thanks

**Comment by ruthtxh** [comment]
Hi @limengtaylor for the unable to access jarfile error, can you try reinstalling TagUI by copying over a fresh copy of the installation src files from [here](https://github.com/kelaberetiv/TagUI/releases/download/v6.110.0/TagUI_Windows.zip).

**Comment by limengtaylor** [comment]
> Hi @limengtaylor for the unable to access jarfile error, can you try reinstalling TagUI by copying over a fresh copy of the installation src files from [here](https://github.com/kelaberetiv/TagUI/releases/download/v6.110.0/TagUI_Windows.zip).

Thank you! now, snap ()-() to snap.png can get snap.png

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant or an issue.
