### ISSUE TITLE
keyboard [ctrl]v  pastes in address bar - set textbox in focus using visual automation

### ISSUE THREAD

**Issue by limengtaylor** [aisingapore/TagUI#1274]
https://www.wangeditor.com/demo/index.html
wait 2
click //*[@id="w-e-element-0"]
clipboard('some text')
keyboard [ctrl]v
wait 2
snap page to editor.png
![image](https://user-images.githubusercontent.com/36980796/184613231-0381e2a2-ec6a-45dd-889d-205889d3b976.png)

**Comment by limengtaylor** [comment]
> https://www.wangeditor.com/demo/index.html wait 2 click //*[@id="w-e-element-0"] clipboard('some text') keyboard [ctrl]v wait 2 snap page to editor.png ![image](https://user-images.githubusercontent.com/36980796/184613231-0381e2a2-ec6a-45dd-889d-205889d3b976.png)

i find the reason is that 'the web url is selected,the focus is on the web address bar'

**Comment by ruthtxh** [comment]
Hi @limengtaylor 
You have to set the textbox in focus first by doing a visual automation click before you use keyboard step.
First you have to take a snapshot of the textbox and put in the same folder as your flow file. Then do:
```
click textbox.png
keyboard [ctrl]v
```

sample of textbox.png:
![image](https://user-images.githubusercontent.com/40910744/184834754-393dc978-cbf3-40f4-92d0-2e9a72766d65.png)

FYI the visual automation click will happen right in the center of the image.

**Comment by limengtaylor** [comment]
> textbox

Thanks ,it can solve the problem when there is a input 或 textarea,but there are some text-editor like TinyMC,Ckeditor,wangeditor,it doesn't has input or textarea.

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant or an issue.
