### ISSUE TITLE
click image in different Image resolution,sometimes it can't find the image

### ISSUE THREAD

**Issue by limengtaylor** [aisingapore/TagUI#1275]
just like 'click table.png',when i reset the Image resolution,it can't find the table.png

**Comment by ruthtxh** [comment]
Hi @limengtaylor the image should be 72ppi for it to match.

**Comment by limengtaylor** [comment]
> Hi @limengtaylor the image should be 72ppi for it to match.

becuase i need to choose a file， i use screenshot to click it . But i use PS to get 72ppi Image ,it still can't be finded when i change the Image resolution of Computer

**Comment by ruthtxh** [comment]
Hi @limengtaylor some other things you can try is to change the windows zoom and browser zoom to 100%.
Just to check, visual automation works on your computer?

**Comment by limengtaylor** [comment]
> Hi @limengtaylor some other things you can try is to change the windows zoom and browser zoom to 100%. Just to check, visual automation works on your computer?

No，it doesn't work。
i want know  how the visual automation identify the Image.

**Comment by limengtaylor** [comment]
> > Hi @limengtaylor some other things you can try is to change the windows zoom and browser zoom to 100%. Just to check, visual automation works on your computer?
> 
> No，it doesn't work。 i want know how the visual automation identify the Image.

**Comment by ruthtxh** [comment]
Hi @limengtaylor is this a different machine? Seems like you are able to do visual automation from this issue https://github.com/aisingapore/TagUI/issues/1274. If it is the same machine, most likely the image resolution is not matching. Can you share more on which tool you used to take the snapshot?

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant or an issue.
