### ISSUE TITLE
how to click 'rate' and 'slider' in tagui - try this

### ISSUE THREAD

**Issue by limengtaylor** [aisingapore/TagUI#1277]
https://ant.design/components/rate-cn/
![image](https://user-images.githubusercontent.com/36980796/186064040-4d3a14c0-d439-42f5-9047-e64f296a676c.png)
how to spot it's half or not when i want to click?
https://ant.design/components/slider-cn/
![image](https://user-images.githubusercontent.com/36980796/186064611-6e483578-6acf-432d-98e4-ed4bcc2b645a.png)
how to set different value by click in tagui

**Comment by ruthtxh** [comment]
Hi @limengtaylor you can try this for the stars:
```
https://ant.design/components/rate-cn/
star = 0
for n from 1 to 5
	read //*[@id="components-rate-demo-half"]/section[1]/ul/li[`n`]/@class to x
	if x contains "ant-rate-star-half"
		star = star + 0.5
	if x contains "ant-rate-star-full"
		star = star + 1
echo `star`
```

For slider you can try something like this:
```
https://ant.design/components/slider-cn/
dom begin
document.getElementsByClassName("ant-slider-track")[0].style.width = "100%"
document.getElementsByClassName("ant-slider-handle")[0].style.left = "100%";
document.getElementsByClassName("ant-slider-handle")[0].ariaValueNow = "100"
dom finish
```

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant or an issue.
