### ISSUE TITLE
UNKNOWN ERROR - ILLEGAL OPTIONS

### ISSUE THREAD

**Issue by YANLINGLOW** [aisingapore/TagUI#1280]
<img width="554" alt="Screenshot 2022-09-18 at 8 14 34 PM" src="https://user-images.githubusercontent.com/113837492/190901573-485c42d0-61cf-49ae-a422-176d49a32137.png">

**Comment by ruthtxh** [comment]
Hi @YANLINGLOW 

I think you are missing a space between -sf and your paths, try this:
```
sudo ln -sf /Users/pamela/Downloads/tagui/src/tagui /usr/local/bin/tagui
```

**Comment by YANLINGLOW** [comment]
Hi Ruth,

Moving on to the next steps, it show the below:


***@***.*** ~ % sudo ln -sf /Users/pamela/Downloads/tagui/src/tagui /usr/local/bin/tagui

Password:

***@***.*** ~ % tagui /Users/pamela/Downloads/tagui/flows/samples/1_google.tag

/usr/local/bin/tagui: line 326: php: command not found

env: python: No such file or directory


could you help please?


thankyou

________________________________

**Comment by ruthtxh** [comment]
Hi @YANLINGLOW  we have users who experienced this same error and reported that installing python helped. Can you try and let us know?

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant or an issue.
