### ISSUE TITLE
if exist(..)  is not executing as intended.

### ISSUE THREAD

**Issue by evanpeng-life** [aisingapore/TagUI#1281]
**code:**
`https://www.lowes.com
timeout 15

logged = exist('//*[@id="account-name" and not(contains(text(), "Sign In"))]')
echo `logged`

if exist('//*[@id="account-name" and not(contains(text(), "Sign In"))]')
    echo Signin
else
    echo Signout

if logged
    echo Signin
else
    echo Signout`

**printed log:**
https://www.lowes.com - Lowe’s Home Improvement

true
Signout
Signin

https://www.lowes.com/ - Lowe’s Home Improvement
FINISH - automation finished - 21.4s

Please tell me where I am wrong, thanks!

**Comment by ruthtxh** [comment]
Hi @EvanYiLi you can try the following
```
https://www.lowes.com/
read //*[@id="account-name"]/text() to status
if (status!="Sign In")
	echo Signin
else
	echo Signout
```

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant or an issue.
