### ISSUE TITLE
Is it possible to integrate TagUI to some other testing framework?

### ISSUE THREAD

**Issue by gauravgandhi1315** [aisingapore/TagUI#1283]
I am already using another testing framework to do end to end testing. Is it possible if I can integrate `TagUI` with my existing framework where I would be able to write tests in english language?

**Comment by ruthtxh** [comment]
Hi @gauravgandhi1315 can you share more on how you intend to integrate TagUI with your other test framework?

**Comment by gauravgandhi1315** [comment]
Suppose if I use selenium or playwright, can I integrate TagUI within the same framework?

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant or an issue.
