### ISSUE TITLE
How to pass a parameter  in another TagUI flow

### ISSUE THREAD

**Issue by petertsneg** [aisingapore/TagUI#1286]
main.tag
```
echo `p1`
tagui subTagui.tag `p1`
```
subTagui.tag
```
echo `p1`
```
cmd run tagui flow
```
PS D:\robot\testParameter>tagui main.tag test
ERROR - file not found for step tagui subTagui.tag `p1`
ERROR - automation aborted due to above 
```

**Comment by ruthtxh** [comment]
Hi @petertsneg your child flow (subTagui.tag) can access all variables in the parent flow (main.tag).
So doing the following will do:
main.tag
```
tagui subTagui.tag
```

subTagui.tag
```
echo `p1`
```
Do make sure that your subflow is in the same folder as your parent flow if you want to use relative file path such as this.

**Comment by petertsneg** [comment]
Hi @ruthtxh ,
test ok, thank~
