### ISSUE TITLE
Can I  break out from a loop

### ISSUE THREAD

**Issue by gallex** [aisingapore/TagUI#1288]
I want to break out from a loop when some condition match, is it possible?

**Comment by petertsneg** [comment]
```
a = 0
for n from 1 to 10
  a = a + 1
  echo `a`
  if a>5
    break;
```

**Comment by gallex** [comment]
> ```
> a = 0
> for n from 1 to 10
>   a = a + 1
>   echo `a`
>   if a>5
>     break;
> ```

Thans
