### ISSUE TITLE
hover/click does not real move mouse

### ISSUE THREAD

**Issue by gallex** [aisingapore/TagUI#1291]
When use hover/click on a element, the function is OK, but I found the mouse position does not changed( synchronized with what in sikuliX) .  

For example,  after hover/click a element,  then  use ```echo `mouse_xy()` ``` return value is not the element position.

**Comment by marcelocecin** [comment]
can you share the code and attach some prints ?

**Comment by gallex** [comment]
I find the reason,  use some thin like this ``` hover xxxx.png``` instead of   ```hover [web/xpath]```。

first form use Vision/Sikuli  engine and second use Chrome  engine.

**Comment by ruthtxh** [comment]
Hi @gallex can you check that your windows zoom is set to 100%?

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant or an issue.
