### ISSUE TITLE
中文乱码 - user's text editor issue

### ISSUE THREAD

**Issue by Mark110513** [aisingapore/TagUI#1293]
Hi，遇到个问题，英文输入没有问题，中文会乱码
试过以下两种方式，情况都是一样的

1、clipboard + keyboard 方式：
saleName = "张三"
clipboard(saleName)
click //div[@prop="saleName"]//input[@class="ant-input"]
keyboard [ctrl]v

2、type as 方式
type //div[@prop="saleName"]//input[@class="ant-input"] as "张三"

![image](https://user-images.githubusercontent.com/98000952/196874086-98f70dcd-8d84-4f03-9eac-3fd1e3129182.png)

请问需要怎么解决中文乱码问题？

**Comment by ruthtxh** [comment]
Hi @Mark110513 I tried replicating this issue but I am able to output chinese characters for both type step and keyboard step. Can you share more on what is your pc language settings, and perhaps which text editor are you using for TagUI?

**Comment by Mark110513** [comment]
OK了，tag脚本需要使用系统自带的notepad去编辑。
感谢！

**Comment by Mark110513** [comment]
OK了，编辑器的问题
感谢！
