### ISSUE TITLE
TagUI from docker container error launching Chrome

### ISSUE THREAD

**Issue by EvanYiLi** [aisingapore/TagUI#1294]
I got the error as below. 
`work@651766aebdf0:~$ tagui tagui/flows/samples/1_google.tag
/home/work/tagui/src/tagui: line 398:  1769 Trace/breakpoint trap   $chrome_command --user-data-dir="$TAGUI_DIR/chrome/tagui_user_profile" $chrome_switches $window_size $headless_switch $no_sandbox_switch > /dev/null 2>&1`

**Comment by balicheng** [comment]
hi, I meeting the same error when i run rpa on centos for . Have you solved the problem? Hope for your answer, than you very much!
