### ISSUE TITLE
If the Excel file name includes Chinese, or the sheet name is Chinese. Tagui does not work.

### ISSUE THREAD

**Issue by KyleXYY** [aisingapore/TagUI#1295]
run cmd /c chcp 65001
timeout 100
variable = [D:\测试.xlsx]测试!A:A
echo `variable[1]`

**Comment by ruthtxh** [comment]
Hi @KyleXYY yes I can replicate this issue, there is no support for excel file name in Chinese for excel step. We will look into this.

**Comment by petertsneg** [comment]
Hi @KyleXYY , @ruthtxh 
Traditional Chinese test is OK.
``` js
variable = [D:\robot\test1\中文\中文.xlsx]工作表1!A:A
echo `variable[0]`
```
- Is it possible that the array index starts from 0
- Echo variables should be quoted

**Comment by KyleXYY** [comment]
> * Is it possible that the array index starts from 0

Excel A:1 to A4:
#支付宝账务明细查询
#账号：[xxxxxxxxxxxxxxxxxxxxxx]
#起始日期：[2022年08月01日 00:00:00]   终止日期：[2022年09月01日 00:00:00]
#-----------------------------------------账务明细列表----------------------------------------

> * Echo variables should be quoted

Without \\ in this editor,  \' miss

If no Chinese I will get the expected result aroud 10 minutes, otherwise output "undefine" about 3 seconds.

**Comment by petertsneg** [comment]
Hi @KyleXYY 
have you tried this #1199

**Comment by KyleXYY** [comment]
no yet, but I cannot change env to UTF8 since this Script must run at the default  windows env for Others.

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant or an issue.
