### ISSUE TITLE
MS Word Addin Question

### ISSUE THREAD

**Issue by petertsneg** [aisingapore/TagUI#1297]
hi @ruthtxh 
try TagUI WordAddIn V3.16 

[run_error.webm](https://user-images.githubusercontent.com/82127495/199374567-e16d6b13-4785-4c2a-89c3-2b3dddcb02e0.webm)

**Comment by ruthtxh** [comment]
Hi @petertsneg thanks for reporting this, we have added the fix [TagUI WordAddIn V3.17](https://storage.googleapis.com/tagui-dependencies/TagUI%20WordAddIn/TagUIWordAddInSetupV3.17.zip)

Link to issue #1282

**Comment by petertsneg** [comment]
Hi @ruthtxh 
Test TagUI WordAddIn V3.17 OK .
Thanks for the quick reply.
