### ISSUE TITLE
Can tagui support running on windows terminal server?

### ISSUE THREAD

**Issue by petertsneg** [aisingapore/TagUI#1301]
Hi @ruthtxh ,

our Users environment
OS：Windows Server 2012 R2 64bits
Users connect to Terminal Server through RDP to operate.

Can tagui support running on windows terminal server?
Can multiple users execute at the same time?

sorry for your troubles.

**Comment by ruthtxh** [comment]
Hi @petertsneg I have not tested it on windows server but it should be able to work. What do you mean by multiple users execute at the same time? If you refer to TagUI process, you can run one process at a time.

**Comment by petertsneg** [comment]
Hi @ruthtxh ,
What do you mean by multiple users execute at the same time?
Two users execute tagui simultaneously on windows terminal server.

I tested and found that a User's program will be stuck when executing another User's program.

**Comment by petertsneg** [comment]
Hi @ruthtxh ,
Do I need to provide any other information?

**Comment by ruthtxh** [comment]
Hi @petertsneg from your video you are using the Word AddIn and the end_processes command is ran first before the start of each TagUI process, hence killing any existing run that is executed halfway. In summary, you can only run one at a time
