### ISSUE TITLE
TagUI - RUN misbehave with parameters between double quote

### ISSUE THREAD

**Issue by GarneshMike** [aisingapore/TagUI#1306]
Hi there, 

I'm running an external command with arguments using RUN function as below. 
Command   : "C:\tagui\set_focus.exe"
Argument 1 : --windows_name="test file"
Argument 2 : --windows_mode="restore"

It seems the double quote does not have any impact on parsing the arguments.
Is there any workaround available. Thanks in advance.

//TagUI Script
run "C:\tagui\set_focus.exe" --windows_name="test file" --windows_mode="restore"
echo `run_result`

//Results
START - automation started - Fri Nov 25 2022 16:24:13 GMT+0800 (Malay Peninsula Standard Time)
run "C:\tagui\set_focus.exe" --windows_name="test file" --windows_mode="restore"
usage: set_focus.exe [-h] --windows_name WINDOWS_NAME --windows_mode
                     WINDOWS_MODE
set_focus.exe: error: unrecognized arguments: file"

FINISH - automation finished - 0.9s

**Comment by ruthtxh** [comment]
Hi @GarneshMike can you try this to run your external programme?
```
run cmd /c start C:\\tagui\\set_focus.exe
```

**Comment by marcelocecin** [comment]
https://github.com/aisingapore/TagUI/issues/1135

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant of an issue.
