### ISSUE TITLE
TagUI - KEYBOARD for [SHIFT][DOWN] not working - try vision step

### ISSUE THREAD

**Issue by GarneshMike** [aisingapore/TagUI#1307]
Hi there, 

The TagUI keyboard function is not executing SHIFT + DOWN key instead only DOWN key are being entered. 

TagUI Script
keyboard [SHIFT][DOWN]

Thanks in advance.

**Comment by ruthtxh** [comment]
Hi @GarneshMike you can try this:
```
vision type(Key.DOWN, KeyModifier.SHIFT)
```

**Comment by GarneshMike** [comment]
hi @ruthtxh 

Unfortunately not working.

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant of an issue.
