### ISSUE TITLE
Read specific style value with TagUI - try dom step to get computed style

### ISSUE THREAD

**Issue by Flipsand** [aisingapore/TagUI#1308]
Hi,
i want to know if it's possible to read a specific style value with TagUI. As example i open up the TagUI Live Mode. Then i open any Website. Then i do inspect that website with F12 and identify a needed XPath (right click with my mouse and then select "Copy>Copy XPath". With this XPath i can do "show XPath" in my Live Mode and get the expected result. So far so good:)

If i do a right click at this selected point and select "Copy>Copy styles" i am able to "STRG+V" the result in Notepad or something else. The given output is the styles part of the selected entry. My question is: Is it possible to get the styles information with TagUI into any kind of string/variable or maybe is it possible to get some part of the styles info, as example a part of the styles info has some value for "background-position", can i get this value with TagUI separate?

Target: Get the value "-7df" from the style which is shown when selecting the class="a5p-tune a5p-tune-d", but how?:

Chrome Browser after F12 and selecting some part, here it's:
`<span class="a5p-tune a5p-tune-d"></span>`
XPath which is copied when right click and "Copy>Copy XPath":
//*[@id="a5plan-wrap"]/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[1]/div/span[3]/span
Existing style which is shown in Browser for that entry:
element.style {
}
#a5plan-wrap .a5p-tune.a5p-tune-d {
    background-position: -7df 0;
}

When i just use "show styles" in Live Mode i get the website styles. I tried around and was not able to get some solution. Maybe someone has one. 

Best regards

**Comment by marcelocecin** [comment]
can you share the url?

**Comment by Flipsand** [comment]
In short you just can try in Live Mode:
https://github.com/aisingapore/TagUI
show style

As the result shows among other things the entry "height:". Try to get this value for "height:" alone to a variable or something like that. In Browser with inspection (F12) some stuff is listed under the element.style.  The goal is how to get some specific entry values.

**Comment by marcelocecin** [comment]
maybe entering the [html code of the page](https://github.com/aisingapore/TagUI/issues/585) and then applying some regex extraction is more effective

**Comment by ruthtxh** [comment]
Hi @Flipsand as how the styles are rendered differs cross-browser, perhaps you can try and get the computed style. Here's an example:

```
https://github.com/aisingapore/TagUI
dom return window.getComputedStyle(document.getElementById('code-tab')).width
echo `dom_result`
```

**Comment by Flipsand** [comment]
Thanks @ruthtxh this info help me further.
