### ISSUE TITLE
Increasing the typing speed with TagUI is not working

### ISSUE THREAD

**Issue by Jonsch-HTL** [aisingapore/TagUI#1309]
I'm currently working on my thesis project, where the task i have to automate is very time sensitiv. I already changed the tool to browser delay to 0, and now I want to change the typing from "character by character" to "insert" the whole string at once.

I already tried to do this by changing the chrome.sendKeys function in tagui_headers.js but for some reason it doesn't work for me:

![Bild_2022-12-17_114549242](https://user-images.githubusercontent.com/79207600/208237998-876d0bcd-3e37-4dd9-9436-143025276200.png)

Anyone has got an idea what i could do?

**Comment by Flipsand** [comment]
Maybe it could help when you use the clipboard. 
Example:
my_string = 'text i want to insert as once not char by char'
clipboard('`my_string`')
keyboard [ctrl]v

**Comment by Jonsch-HTL** [comment]
Yea, I've already seen this kind of solution, but I just wanted to know if somebody got an idea on how to get done, the way i wanted to do it, because this was it's kind of more structured code

**Comment by ruthtxh** [comment]
Hi @Jonsch-HTL, try turbo mode?
```
tagui flow.tag -t
```
https://tagui.readthedocs.io/en/latest/advanced.html#turbo-mode-to-run-10x-faster

**Comment by Jonsch-HTL** [comment]
Yeah i hear about that, the problem is, for my project i have to start the automation through a web application, so i have to work with the cmd file for my tagui automation, and im not sure if i can lead the cmd file to start with turbo mode...

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant of an issue.
