### ISSUE TITLE
Tagui Python: Is there a way to increase the speed of the Tagui extension for python

### ISSUE THREAD

**Issue by Jonsch-HTL** [aisingapore/TagUI#1310]
I'm working on a projekt in python, to automate a carting process, which of course is very time sensitiv. When i now start an automation with Tagui itself, it is already pretty fast, because I modded the header files for clicking and typing, but now when I use the Tagui extension for python it is way to slow. Since the extension uses the Tagui I've installed before it should also work with the modded header files, or am i wrong. If thats not the case, is there a way to increase clicking and typing speed for Tagui-Python or to reduce the Delay between the single steps?

**Comment by ruthtxh** [comment]
Hi @Jonsch-HTL you can try turbo mode for RPA for python, more details on syntax [here](https://github.com/tebelorg/RPA-Python)

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant of an issue.
