### ISSUE TITLE
seems that ask_result variable is not known

### ISSUE THREAD

**Issue by ChrispyWugen** [aisingapore/TagUI#1314]
Hi,

i am having trouble using the "ask" step to get user input and saving it to another temporary variable.
I tried this code snippet:

ask password?
password = `ask_result`
echo `password`

It always outputs "+ask_result+" to the console.

If I try this code snippet, similar to the example shown in the reference documentation, I get the expected result (user input string is printed to console):

ask username?
echo `ask_result`

Do you have any suggestions how to archiv my goal and save the user input from ask_result variable to my temporary variable?

Thank you very much

Kind regards

Chris

**Comment by ruthtxh** [comment]
Hi @ChrispyWugen, when you save the ask_result to a temporary variable, you do not have to use backticks.
```
ask password?
password = ask_result
echo `password`
```

**Comment by marcelocecin** [comment]
hi Chris, you can use `vision` too:
```
username = 'chris'
vision_step('username = "' + username + '"');
vision output_sikuli_text(input("Hi "+username+", please enter your secret:", hidden = True))
quick_pass = fetch_sikuli_text()
echo `quick_pass`
```
https://sikulix-2014.readthedocs.io/en/latest/interaction.html

**Comment by ChrispyWugen** [comment]
Hi Ruth,

Thank you very much. That worked for me:
![snippet](https://user-images.githubusercontent.com/38278778/215752431-a792549f-d666-4bf6-8334-2439c668daf3.png)

I was confused because all code samples I found (with "type" or "echo")were with backticks
