### ISSUE TITLE
python not working from inside tagui script - see example

### ISSUE THREAD

**Issue by venky652003** [aisingapore/TagUI#1315]
i have installed tagui on windows10. if i write python commands inline  using py begin .. py finish , they are not working.
sample code is below:

string_1 = "hello"
string2 = "world"
string3 = "how are "
string4 = "you"
string5 = ""

py begin
string5 = string3 +string4
print (string5)
py finish

echo `string5`

 pl help

**Comment by ruthtxh** [comment]
Hi @venky652003 

You can try the following:
```

string3 = "how are "
string4 = "you"

py_step('string3 = "' + string3 + '"')
py_step('string4 = "' + string4 + '"')

py begin
string5 = string3 +string4
print (string5)
py finish

string5 = py_result
echo `string5`
```

For more examples on how to pass variables to the py step you can refer to https://tagui.readthedocs.io/en/latest/advanced.html#writing-python-within-flows

**Comment by venky652003** [comment]
thanks . will try.

**Comment by venky652003** [comment]
Thank you so much for your help! I really appreciate it.

**Comment by ruthtxh** [comment]
Closing issue, feel free to reopen if there are further doubts.
