### ISSUE TITLE
use present() function when contains variable then error

### ISSUE THREAD

**Issue by xin911** [aisingapore/TagUI#1317]
![image](https://user-images.githubusercontent.com/11419372/219363982-b80ed81c-531e-4f07-90a3-7a4d88b39446.png)

when the xpath contains variable, present() function work not correct.
example:
>>show //*[@id="main"]/div/div/div[2]/div[6]/div[2]/div/div[1]
工作台 修改分组与排序
>>echo `present('//*[@id="main"]/div/div/div[2]/div[6]/div[2]/div/div[1]')`
true
>>n = 1
show //*[@id="main"]/div/div/div[2]/div[6]/div[2]/div/div[**`n`**]
工作台 修改分组与排序
>>echo `present('//*[@id="main"]/div/div/div[2]/div[6]/div[2]/div/div[**`n`**]')`
ERROR - expected token ')'
>>echo `present('//*[@id="main"]/div/div/div[2]/div[6]/div[2]/div/div[**`+n+`**]')`

>>

how can I get the answer..?

**Comment by xin911** [comment]
echo `present(`变量`)`
false变量
echo `present(变量)`
true
echo `present(''变量'')`
ERROR - expected token ')'
echo `present(\'\'变量)`
ERROR - expected token ')'
echo `present(''+变量)`
true
done

=========
如果不是被产品和领导逼的这么紧，真应该看看代码的。
因为if present 和read混用，让我模糊了变量和字符串的边界。
近期还要继续努力学习算法和es啊。共勉一下

**Comment by ruthtxh** [comment]
Hi @xin911, to concatenate the variables in the if present condition, you can take a look at the following example:

```
https://www.google.com/
click //*[@id="SIvCob"]/a[1]
甲= '搜索'
if present("//*[contains(text()," + 甲 + ")]")
	echo test3
else
	echo not pass 3
```
