### ISSUE TITLE
problem in passing parameters to python from tagui code - please help

### ISSUE THREAD

**Issue by venky652003** [aisingapore/TagUI#1318]
Hi. The following code works well as a pure python code. WHen a wrap tagui code around and pass the variables through "py_step" it just hangs at the py_step. I tried to comment out the entire python code , but it still hangs after py_step. Pl help.
my_path = flow_path
echo `my_path`
jpc_filename = "FEB23"      

pfile = {"my_path":my_path,"jpc_filename":jpc_filename}
js json_pfile = JSON.stringify(pfile)
echo `json_pfile`
py_step("json_pfile = '" + json_pfile + "'")

py begin

import tabula
import os
import re
import json

pfile = json.loads(json_pfile)
py_path = pfile["my_path"]
py_jpc_filename = pfile["jpc_filename"]

#obtain the path

py_path = py_path + "/"
jpc_prepend = "JPC_.."
jpc_append = ".pdf"

final_file = jpc_prepend+py_jpc_filename+jpc_append
#setup the match value -which we will get from the table

match_string = final_file
print(match_string)

#setup the command string for giving the os command
command = "dir py_path  *.pdf >scrap.txt "
os.system (command)   # we got all matching files in a file

#now we read the file into which we have collected the output of directory command
file_name = py_path+"scrap.txt"
file_handle = open(file_name,"r")
file_var = file_handle.read()
file_handle.close()

#now we search for the pdf file that we are interested in
matched_string = re.search(match_string,file_var)
file_temp = matched_string.group()

#we will prepend the path name to the pdf filename that we got finally
file_var = py_path+file_temp

#read the pdf and extarct the tables

tables = tabula.read_pdf(file_var, lattice = True, pages= 'all')
#print(tables)
py_finish
echo `py_result`

**Comment by ruthtxh** [comment]
Hi @venky652003 your ending block for py step should be:
py finish instead of py_finish

Let me know if this helps.

**Comment by venky652003** [comment]
thanks. It was a really silly error but somehow I could not see it. Thanks for pointing it  out.
