### ISSUE TITLE
Help me to install tagui in my linuxmint

### ISSUE THREAD

**Issue by Bala-periannan** [aisingapore/TagUI#1319]
Please find the below command. I am trying to pass this for 3 days but i couldn't find the solution. I am very close to the end.

bala@bala-HP-Pavilion-dv3-Notebook-PC:~$ tagui /home/bala/Desktop/tagui/flows/samples/1_google.tag
/usr/local/bin/tagui: line 261: /home/bala/Desktop/tagui/flows/samples/1_google.tag.log: Permission denied
chmod: changing permissions of '/home/bala/Desktop/tagui/flows/samples/1_google.tag.log': Operation not permitted
rm: remove write-protected regular empty file 'tagui_chrome.in'?

**Comment by kensoh** [comment]
Closing but please ping back if this is still relevant of an issue.
