### ISSUE TITLE
Open the specified browser but do not perform any automated actions afterwards

### ISSUE THREAD

**Issue by gihugui** [aisingapore/TagUI#1320]
After modifying file tagui.cmd , it is possible to open the specified browser。
The browser I am opening is also based on the Chromium engine

print start  same as ""start" "C:\\Program Files\\fxbrowser2\\fxbrowser.exe" --act-id=0000  --user-data-dir=C:\Users\Admin\AppData\Local\fxbrowser\platform\0000   --remote-debugging-port=9222 about:blank --window-size=1366,842"

**Comment by gihugui** [comment]
![image](https://user-images.githubusercontent.com/43509035/220082321-a0bf8920-53b6-40c5-a332-ebcc61c1c4fe.png)

**Comment by ruthtxh** [comment]
Hi @gihugui I am not sure what your query is about, but by default the chrome browser opens every time you run an automation.
You can also use the run step within your flow to launch an application https://tagui.readthedocs.io/en/latest/reference.html#run
