### ISSUE TITLE
present() cannot work when xpath contains multi-conditions - fixed

### ISSUE THREAD

**Issue by xin911** [aisingapore/TagUI#1321]
multi-conditions:
echo `present('//tr[2]/td[5][not(starts-with(@class,"dp_not_in_month_selectable")) and not(@class="dp_disabled") and not(@class="dp_not_in_month")]/div[@class="Zebra_DatePicker_dataWrap"]')`
----echo return true

if present('//tr[2]/td[5][not(starts-with(@class,"dp_not_in_month_selectable")) and not(@class="dp_disabled") and not(@class="dp_not_in_month")]/div[@class="Zebra_DatePicker_dataWrap"]')
	echo test3
else
	echo not pass 3
====
the same condition, echo return true. **But**, result "return not pass 3".
try several times, "if present" cannot support multi-conditions which used not() .
when I use "show xpath" or "click xpath" command, it work well.

**Comment by xin911** [comment]
three "if present" conditions, use present() or present() or present.

**Comment by ruthtxh** [comment]
Hi @xin911 yes we can replicate this, root cause seems like when running with the if condition step, the locator variable converts the text "and" to "&&" making the xpath invalid.

**Comment by xin911** [comment]
> Hi @xin911 yes we can replicate this, root cause seems like when running with the if condition step, the locator variable converts the text "and" to "&&" making the xpath invalid. ![image](https://user-images.githubusercontent.com/40910744/220872863-17d4d6d6-bbae-4fcb-9e53-0f6bd1d5307e.png) ![image](https://user-images.githubusercontent.com/40910744/220872924-f0855c56-e8b5-43d9-a920-1ae8c4cbae12.png)
> 
> In tagui_parse.php, this handling does the replacement, seeing if it makes sense to make exception for text within xpath: ![image](https://user-images.githubusercontent.com/40910744/220872303-0c03c70e-57e8-4a1e-8473-46362cf3112b.png)

then, how could I use the fixed version..? 
tagui update?
