### ISSUE TITLE
number of step { does not tally with with } error - try this

### ISSUE THREAD

**Issue by venky652003** [aisingapore/TagUI#1322]
hi,
when I run this code in tagui , i get the above error. what could be the error in the code?

matter = 3
for n from 1 to 5
{

	echo "n = " `n`
        echo `matter`

}

**Comment by ruthtxh** [comment]
Hi @venky652003, please try this:
```
matter = 3
for n from 1 to 5
	echo "n = " `n`
	echo `matter`
```
Note that the syntax has changed from curly braces to indentations and you would have to stick to the same indentation throughout the flow. i.e. if you choose to use tabs, then it should only be tabs instead of spaces in multiples of 2 (vice versa).

**Comment by venky652003** [comment]
Thanks a lot. Problem solved. I
