### ISSUE TITLE
Remove comma(,) after read data from web - try this

### ISSUE THREAD

**Issue by keat0101** [aisingapore/TagUI#1323]
Hi, I have some problem when I need to remove the comma from the value inside **volValue**. Any recommendation to remove the comma inside the volValue? Thanks in advance.

`https://www.bursamalaysia.com/

dump Code, Name, LastDone, Change, Vol(00) to Top-gainer.csv
rows = count('//*[@id="pills-gainer"]/table/tbody/tr')

for row from 1 to rows
	read //*[@id="pills-gainer"]/table/tbody/tr[`row`]/td[1]  to codeValue
	read //*[@id="pills-gainer"]/table/tbody/tr[`row`]/th/div/a to nameValue
	read //*[@id="pills-gainer"]/table/tbody/tr[`row`]/td[2] to lastDoneValue
	read //*[@id="pills-gainer"]/table/tbody/tr[`row`]/td[3] to changeValue
	read //*[@id="pills-gainer"]/table/tbody/tr[`row`]/td[4] to volValue
	//remove comma(,) inside the volValue
	py import re
	py string vol = re.sub(",", "",volValue)
	write `codeValue`,`nameValue`,`lastDoneValue`,`changeValue`, `vol` to Top-gainer.csv`

**Comment by ruthtxh** [comment]
Hi @keat0101 you can try this:
```
https://www.bursamalaysia.com/

dump Code, Name, LastDone, Change, Vol(00) to Top-gainer.csv
rows = count('//*[@id="pills-gainer"]/table/tbody/tr')

for row from 1 to rows
	read //*[@id="pills-active"]/table/tbody/tr[`row`]/td[1] to codeValue
	read //*[@id="pills-active"]/table/tbody/tr[`row`]/th/div/a to nameValue
	read //*[@id="pills-active"]/table/tbody/tr[`row`]/td[2] to lastDoneValue
	read //*[@id="pills-active"]/table/tbody/tr[`row`]/td[3] to changeValue
	read //*[@id="pills-active"]/table/tbody/tr[`row`]/td[4] to volValue
	js volValue = volValue.replace(/[,]/g, '')
	write `codeValue`,`nameValue`,`lastDoneValue`,`changeValue`, `volValue` to Top-gainer.csv
```

**Comment by keat0101** [comment]
Thanks @ruthtxh, I also have found out one solution with the use of **csv_row()**. The sample code is:

`https://www.bursamalaysia.com/

dump Code, Name, LastDone, Change, Vol(00) to Top-gainer.csv
rows = count('//*[@id="pills-gainer"]/table/tbody/tr')

for row from 1 to rows
	read //*[@id="pills-gainer"]/table/tbody/tr[`row`]/td[1]  to codeValue
	read //*[@id="pills-gainer"]/table/tbody/tr[`row`]/th/div/a to nameValue
	read //*[@id="pills-gainer"]/table/tbody/tr[`row`]/td[2] to lastDoneValue
	read //*[@id="pills-gainer"]/table/tbody/tr[`row`]/td[3] to changeValue
	read //*[@id="pills-gainer"]/table/tbody/tr[`row`]/td[4] to volValue
	topgainer = [codeValue,nameValue,lastDoneValue,changeValue,volValue]
	write `csv_row(topgainer)` to Top-gainer.csv`

**Comment by keat0101** [comment]
Thanks @ruthtxh.
