### ISSUE TITLE
api url error - unable to replicate error for now

### ISSUE THREAD

**Issue by xin911** [aisingapore/TagUI#1324]
api https://work.weixin.qq.com/wework_admin/message/getByMsgId?lang=zh_CN&f=json&ajax=1&timeZoneInfo%5Bzone_offset%5D=-8&random=0.7466647219076441&msgid=7205874282309574648&appid=5629501896578988&_d2st=a7965363
ERROR - nETWORK_ERR: XMLHttpRequest Exception 101

![image](https://user-images.githubusercontent.com/11419372/222746255-fcb8e608-1902-403e-ac8f-ac4a4723780c.png)

**Comment by xin911** [comment]
cors or samesite...?

**Comment by ruthtxh** [comment]
Hi @xin911, I tested the api and this is the response I got
![image](https://user-images.githubusercontent.com/40910744/223032729-2a32f3ce-4a24-4f8b-baf6-78ba97b4fd48.png)

**Comment by xin911** [comment]
> Hi @xin911, I tested the api and this is the response I got ![image](https://user-images.githubusercontent.com/40910744/223032729-2a32f3ce-4a24-4f8b-baf6-78ba97b4fd48.png)

yes, you got the correct response, but why I got the error.
my chrome version is 108.0.5359.98 (x86_64), is it the reason?

**Comment by xin911** [comment]
> Hi @xin911, I tested the api and this is the response I got ![image](https://user-images.githubusercontent.com/40910744/223032729-2a32f3ce-4a24-4f8b-baf6-78ba97b4fd48.png)

![image](https://user-images.githubusercontent.com/11419372/223314309-c9fbb8ba-2858-4f91-95f6-ffa34f308249.png)

**Comment by xin911** [comment]
when I add a global js, and add api http comment line, the error is fixed.

**Comment by xin911** [comment]
The source code feels strange. I didn't understand the specific meaning. keep learning
