### ISSUE TITLE
read and write excel error - excel step for excel app, not numbers app

### ISSUE THREAD

**Issue by xin911** [aisingapore/TagUI#1325]
[Monthly Report.xlsx]August!E10 = 12345
ERROR - expected token ']'
[Monthly Report.xlsx]August!E11 = "Alan"
ERROR - expected token ']'
echo why
why
data_array = [form_data.xlsx]Sheet1!A1
ERROR - expected an identifier but found 'Sheet1' instead
data_array = [form_data.csv]Sheet1!A1
ERROR - expected an identifier but found 'Sheet1' instead

![image](https://user-images.githubusercontent.com/11419372/222746785-110669d1-eed6-4594-a027-026331feb371.png)

**Comment by ruthtxh** [comment]
Hi @xin911 yes you would need excel for this to work!

**Comment by xin911** [comment]
> Hi @xin911 yes you would need excel for this to work!

I installed excel on mac, 
![image](https://user-images.githubusercontent.com/11419372/223051256-43353f0c-e610-40ce-8c88-9377c5d43934.png)

still not work.
![image](https://user-images.githubusercontent.com/11419372/223055777-4434bd46-8259-44d7-bcf7-bea488ea8bdf.png)
![image](https://user-images.githubusercontent.com/11419372/223056037-0179e60d-f452-477d-8102-3f160f4ac671.png)
Excel is installed on my mac, but is not actived. Is it the reason..?

**Comment by xin911** [comment]
> > Hi @xin911 yes you would need excel for this to work!
> 
> I installed excel on mac, ![image](https://user-images.githubusercontent.com/11419372/223051256-43353f0c-e610-40ce-8c88-9377c5d43934.png)
> 
> still not work. ![image](https://user-images.githubusercontent.com/11419372/223055777-4434bd46-8259-44d7-bcf7-bea488ea8bdf.png) ![image](https://user-images.githubusercontent.com/11419372/223056037-0179e60d-f452-477d-8102-3f160f4ac671.png) Excel is installed on my mac, but is not actived. Is it the reason..?

I update the tagui version (6.46->6.110) when changing Windows OS, now tagui work well.
I change the OS windows, still the same error. And then, I update the tagui version, 
![image](https://user-images.githubusercontent.com/11419372/224459435-96a2b37f-5d4f-473d-80c1-3f611a503fa7.png)

mac update (6.46->6.110), execute "[Monthly Report.xlsx]August!E10 = 12345", no response. no excel created. Properly the reason is excel which is not actived on my mac.
