### ISSUE TITLE
when use csv, the variable name does not support UTF-8 character

### ISSUE THREAD

**Issue by xin911** [aisingapore/TagUI#1328]
csv header:
房源编号,Contraction,城市,楼盘名称,缴费方式,公共事业单位,户号,表名称,欠费金额,查询人

and I got the runtime js :
![image](https://user-images.githubusercontent.com/11419372/223039266-863eac36-8dcb-4c1a-93a9-a4f6f7c4f655.png)

the variable name does not support Chinese character, so I cannot get the variable value.

**Comment by ruthtxh** [comment]
Hi @xin911 can you try to change your pc settings?
https://github.com/aisingapore/TagUI/issues/1199#issuecomment-1080397995

**Comment by xin911** [comment]
> Hi @xin911 can you try to change your pc settings? [#1199 (comment)](https://github.com/aisingapore/TagUI/issues/1199#issuecomment-1080397995)

windows change chcp, how to change it on mac..?
![image](https://user-images.githubusercontent.com/11419372/223053831-4e78c19d-d720-4ead-b25b-b16a26837443.png)

**Comment by xin911** [comment]
> Hi @xin911 can you try to change your pc settings?

the csv is read well, the Chinese charactor content is read correct.
**But the csv header** when contains Chinese charactor cannot be read well.
![image](https://user-images.githubusercontent.com/11419372/223122639-c199fb0e-5fa4-4095-9c47-7e5f5df618f7.png)

So I'm not quite sure, when I change my pc settings, It will work.
