### ISSUE TITLE
snap opens a folder instead of file if a comment is there on the same line - pl help

### ISSUE THREAD

**Issue by venky652003** [aisingapore/TagUI#1330]
Hi, 
I am facing a problem in saving a webpage screen through snap - code snippet is below:

File_name_old_commodity = "post_page"
http://www.rediff.com
snap page to `File_name_old_commodity`.png                           //save an image of the webpage
img_file = File_name_old_commodity

the comment " //save an image of the webpage" on the same line as the snap command results in a folder named "post_page.png" and file is not created. If a remove the comment , I get the desired result of saving the webpage screen to a file named "post_page.png". I am not able to understand how a comment can disturb the code. Pl help.

**Comment by ruthtxh** [comment]
Hi @venky652003 the comments are identified only when the line starts with //. If you place them in the middle of the line they do not get identified as comments and hence disrupt the step. Hope this help!
