### ISSUE TITLE
How to add chinese word into excel using write?

### ISSUE THREAD

**Issue by keat0101** [aisingapore/TagUI#1333]
I have met a problem when I trying to pass the Chinese word into an excel file using **write** function. But I get a result as picture below:

![image](https://user-images.githubusercontent.com/126844079/225567380-5ef28176-6319-4b11-8990-efe72898f585.png)

So, how to fix it so that it can show Chinese word correctly? 

Thanks in advance.

**Comment by xin911** [comment]
excel_step.vbs encode UTF-8, and you system default encode is GBK.

**Comment by kensoh** [comment]
Is this still a problem? Closing but please ping back if this is still an issue.
