### ISSUE TITLE
Run TagUI in headful mode in a docker container 

### ISSUE THREAD

**Issue by vu29** [aisingapore/TagUI#1336]
I have some tagUI flows that I need to run in a docker container. Now the issue is that when running the flows in headless mode. I get an error saying that the browser is not supported (most likely a mechanism deployed to prevent bots), but running the same flow in headful mode works perfectly fine. So I need to run them in headless mode in docker. Is there any way I can acheive that ?

**Comment by MajorLettuce** [comment]
I needed the same solution, so I packaged it all into a container which is open-source and you are welcome to use: https://github.com/robocat-ai/robocat-base

Please note that it is not production ready and there are several undocumented features (you can check out `parse_arguments` function `scripts/run.sh`).

Feel free to open and issue there if you have any questions.
I hope this will be helpful to you, cheers!

**Comment by pp082** [comment]
your repository is fantastic. it is possible to enable it to work with ARM architecture

**Comment by kensoh** [comment]
I think it can run on Windows, macOS, Linux and Raspberry Pi, all platforms supported by its core JavaScript engine in PhantomJS. But if it is something not runnable for PhantomJS then cannot.

**Comment by kensoh** [comment]
@pp082 I think it can run on Windows, macOS, Linux and Raspberry Pi, all platforms supported by its core JavaScript engine in PhantomJS. But if it is something not runnable for PhantomJS then cannot.

**Comment by kensoh** [comment]
Hi @lexuzieel and @lexuzieel you can run real browser using xvfb on Linux. You can see a Colab example on Ubuntu that I created for RPA for Python package, which runs TagUI underneath - https://colab.research.google.com/drive/1or8DtXZP8ZxJYK52me0dA6O9A1dXKKOE?usp=sharing
