### ISSUE TITLE
post Content-Type

### ISSUE THREAD

**Issue by gitee996** [aisingapore/TagUI#1338]
api post set Content-Type: application/x-www-form-urlencoded is invalid
just application/json?

**Comment by marcelocecin** [comment]
check https://github.com/aisingapore/TagUI/issues/967

**Comment by gitee996** [comment]
> 检查 #967

thanks. my format is correct。 header:['Content-Type: application/x-www-form-urlencoded']    but it is invalid。
I use an online post tool  to test is ok. Tagui Unable to get the correct result

**Comment by gitee996** [comment]
> can you share more details ?

ok
just Tomorrow. I find it 
thanks

**Comment by gitee996** [comment]
api_config = {method:'POST', header:['Accept: application/json','Content-Type: application/x-www-form-urlencoded'], body:{'TB':'003'}};

api some URL
echo `api_result`

**Comment by marcelocecin** [comment]
```
api_config = {method:'POST', header:['Content-type: application/x-www-form-urlencoded'], body:'orem=ipsum&name=binny'};
api https://webhook.site/your_id_here
echo `api_result`
```
![](https://user-images.githubusercontent.com/2955762/227362282-b236168f-b503-4a78-b5a9-1b4183969e9d.png)

**Comment by gitee996** [comment]
> ```
> api_config = {method:'POST', header:['Content-type: application/x-www-form-urlencoded'], body:'orem=ipsum&name=binny'};
> api https://webhook.site/your_id_here
> echo `api_result`
> ```
> 
> ![](https://user-images.githubusercontent.com/2955762/227362282-b236168f-b503-4a78-b5a9-1b4183969e9d.png)

great!!!!! thank you!
