### ISSUE TITLE
How can I save list of names as a variable one by one in loop to use it further? TagUI

### ISSUE THREAD

**Issue by adisar45** [aisingapore/TagUI#1341]
I have a list of names, I want to save one as variable and use it to perform some action and move on to another variable and perform the action with that and so on for the whole list of names. Can you help me ?

**Comment by ruthtxh** [comment]
Hi @adisar45 you can try saving the list to a variable, then use a tagui for loop to access it like this:
```
list = ["a", "b", "c"]
for n from 0 to list.length-1
  echo `list[n]`
```
https://tagui.readthedocs.io/en/latest/main_concepts.html#for-loops
