### ISSUE TITLE
Newbee here - Where can I find Tagui repository of Helper functions

### ISSUE THREAD

**Issue by gurubaba786** [aisingapore/TagUI#1342]
The link https://github.com/kelaberetiv/TagUI#helper-functions takes me to the home page, there is no file or folder names helper functions.
Where can I find these helper functions?
Please help!
Thank you very much

**Comment by edloseee** [comment]
Hi, you can find out more on helper functions in TagUI's documentation here: https://tagui.readthedocs.io/en/latest/main_concepts.html#helper-functions

**Comment by ruthtxh** [comment]
Closing issue for now, feel free to reopen.
