### ISSUE TITLE
py_step  error passing string variable

### ISSUE THREAD

**Issue by xin911** [aisingapore/TagUI#1346]
name = "DZ202305050205"
phone = 1234567
py_step('phone = ' + phone)  // success
py_step('name = ' + name) // error passing string variable.
![image](https://github.com/aisingapore/TagUI/assets/11419372/4e53fe10-0b5b-4ad3-b35e-07b9b181918f)

use py_step('name = "`name`"') instead.

**Comment by ruthtxh** [comment]
Hi @xin911 
When working with strings and py step you can do this:
```
name = 'DZ202305050205'
py_step('name = "' + name + '"')
py print(name)
echo `py_result`
```

**Comment by ruthtxh** [comment]
Closing this for now, feel free to reopen.
