### ISSUE TITLE
Getting this error when running test script 

### ISSUE THREAD

**Issue by nuprince** [aisingapore/TagUI#1351]
hello i don't know if this error has been posted before but i just downloaded tagui and install everything necessary but when i run a test script i get this error.. Used chatgpt to help solve but still not working .. anyone have a clue what i needs to do ... 

/usr/local/bin/tagui: line 262: tagui_r/tagui_r.log: No such file or directory
chmod: tagui_r/tagui_r.log: No such file or directory
/usr/local/bin/tagui: line 263: tagui_r/tagui_r_windows.log: No such file or directory
chmod: tagui_r/tagui_r_windows.log: No such file or directory
/usr/local/bin/tagui: line 264: tagui_py/tagui_py.log: No such file or directory
chmod: tagui_py/tagui_py.log: No such file or directory
/usr/local/bin/tagui: line 265: tagui_py/tagui_py_windows.log: No such file or directory
chmod: tagui_py/tagui_py_windows.log: No such file or directory
/usr/local/bin/tagui: line 266: tagui.sikuli/tagui.log: No such file or directory
chmod: tagui.sikuli/tagui.log: No such file or directory
/usr/local/bin/tagui: line 267: tagui.sikuli/tagui_windows.log: No such file or directory
chmod: tagui.sikuli/tagui_windows.log: No such file or directory
Could not open input file: tagui_parse.php
ERROR - automation aborted due to above

**Comment by kensoh** [comment]
Hi @nuprince is this still an issue? This sounds like some fundamental issue. If it is still an issue can you share more on the OS and how you download TagUI and how you run it, what test script?
