### ISSUE TITLE
How to extract data from a website using TagUI - some possible ideas

### ISSUE THREAD

**Issue by SaitejaAdmin** [aisingapore/TagUI#1353]
I tried to extract data from a website using TagUI but iam getting an error like this
ERROR - cannot find //*[@id="conversation-editor"]/div[11]/div/div[2]/div/div[2]/div[2]/div[1]/div/div[2]/div[2]/div

Please check my code and tell me how to extract data from website
read //*[@id="conversation-editor"]/div[11]/div/div[2]/div/div[2]/div[2]/div[1]/div/div[2]/div[2]/div to text
write `text` to conversia.txt

**Comment by kensoh** [comment]
Hi @SaitejaAdmin it looks like above web element can't be found. 1 possible reason is the layout might change from when you copy out the XPath and running it, another reason could be that is in a frame and you need to use frame step first.
