### ISSUE TITLE
Unable to Click Xpaths within iframes, because iframe names are changing every time - some ideas

### ISSUE THREAD

**Issue by TharunGoud13** [aisingapore/TagUI#1358]
@ruthtxh , I am trying to perform Tagui on conversica website but it has multiple iframes where the iframe names are changing every time. Can anyone help regarding this issue

**Comment by kensoh** [comment]
Hi @TharunGoud13, I see.. One way is if you know JavaScript, to use js step and write code to try to read the iframe name. But otherwise this is really hard. Another way is if you can load the frame URL directly to automate that frame page directly.
