### ISSUE TITLE
Can it specify the created Python virtual environment in the Tagui script?

### ISSUE THREAD

**Issue by wz-dong** [aisingapore/TagUI#1360]
I want to use the specified virtual environment to run the Python code involved in TAGUI. How should I specify the environment?

**Comment by kensoh** [comment]
Hi @wz-dong I'm afraid by default TagUI will just launch `python` command and use the default environment. You can consider modifying tagui\src\tagui.cmd or tagui to change the python command to be something different like `python3 -m venv "my_env_name"` for example mentioned in https://stackoverflow.com/questions/1534210/use-different-python-version-with-virtualenv
