### ISSUE TITLE
How to get name of the latest downloaded file?

### ISSUE THREAD

**Issue by joker21212** [aisingapore/TagUI#1361]
I want to read the name of the latest downloaded file so that I can use further in my code.

**Comment by kensoh** [comment]
Hi @joker21212, I don't think so easily. Some ideas you can try is to see if you can get the name of the file before you download, from some web element. Or you can try to download at some location and use JavaScript code to find the latest file. For JavaScript code you can use js step - https://tagui.readthedocs.io/en/latest/reference.html#js
