### ISSUE TITLE
Difference fron Cucumber.js?

### ISSUE THREAD

**Issue by linonetwo** [aisingapore/TagUI#1363]
I see this project today, seems very simillar to https://cucumber.io/ , is there a feature diff?

**Comment by kensoh** [comment]
Hi @linonetwo I think primarily the use cases are different. TagUI is more for automating processes quickly and in maintainable way. But Cucumber is more for test automation and testing so you can a lot more configuration.

TagUI can do web automation, desktop automation, visual automation, OCR, keyboard and mouse automation out of the box. And users can use different languages other than English language to define the steps to be automated.
