### ISSUE TITLE
run next code giving fault:   F:\tagui\src>tagui  f:\tagui\flows\samples\1_google.tag - missing Windows find command

### ISSUE THREAD

**Issue by gxactest** [aisingapore/TagUI#1365]
F:\tagui\src>tagui f:\tagui\flows\samples\1_google.tag
find: '/i': No such file or directory
find: '/c': No such file or directory
find: 'api http': No such file or directory

START - automation started - Fri Dec 01 2023 17:05:21 GMT+0800 (中国标准时间)

https://www.google.com - Google
type //*[@name="q"] as latest movies[enter]
click (//*[@class="g"])[1]//a
ERROR - cannot find (//*[@class="g"])[1]//a
find: '/c': No such file or directory
find: 'ERROR -': No such file or directory

**Comment by kensoh** [comment]
Hi @gxactest for some reason your PC doesn't have `find` command. It is a standard Windows command. You can try on another PC or your personal PC. Maybe that command is blocked by your company network or anti-virus.
