### ISSUE TITLE
Text not found - maybe that TEST element is really not found, pending details

### ISSUE THREAD

**Issue by Kellesc** [aisingapore/TagUI#1367]
Hello, 

first of all thank you for this great library. I am trying to click on specific text that changes with a variable. Whatever text I input id does not find it.

the command it passes is: echo "[RPA][5] - exist_result = exist('TEST').toString()" with this page open:
![2023-12-23 12_30_42-_new 3 - Notepad++](https://github.com/aisingapore/TagUI/assets/133388064/46b7f21c-5a68-4cd8-b5f3-7755a83e9aff)

it returns "[RPA][ERROR] - cannot find TEST"

am I doing anything wrong? I couls not find anything related.
I am using rpa package that calls tagui([#509](https://github.com/tebelorg/RPA-Python/issues/509))

Thanks

**Comment by kensoh** [comment]
Hi @Kellesc for rpa package you can raise issue at https://github.com/tebelorg/RPA-Python/issues

Above looks like there is really no element with the name, XPath, CSS selector `TEST` so it returns False

**Comment by kensoh** [comment]
If you are referring to using OCR visual automation to click on TEST word on the screen, the syntax is
```
r.click('TEST.png')
```
