### ISSUE TITLE
Is it possible to get name of the latest downloaded file? - get from website or try using JavaScript code

### ISSUE THREAD

**Issue by gauravgandhi1315** [aisingapore/TagUI#1368]

**Comment by kensoh** [comment]
Hi @gauravgandhi1315 I don't think so easily. Some ideas you can try is to see if you can get the name of the file before you download, from some web element. Or you can try to download at some location and use JavaScript code to find the latest file. For JavaScript code you can use js step - https://tagui.readthedocs.io/en/latest/reference.html#js
