### ISSUE TITLE
Is the project no longer under maintenance - I think I want to contribute back

### ISSUE THREAD

**Issue by lrange2001** [aisingapore/TagUI#1371]
Is the project no longer under maintenance? Why hasn't anyone replied to a question asked in the Chinese group chat? The submitted issue has been unresolved for two days

**Comment by kensoh** [comment]
Hi @lrange2001,

I created this project in 2016-2017, AI Singapore maintained it from 2018 to 2023.

Now I'm thinking to continue to maintain it as an open-source community contributor.

For the Chinese group chat, I think it is independently maintained by Kang Yi Wen. Is he still actively supporting TagUI users in China?

**Comment by supercena** [comment]
@kensoh  大佬 ，想看tagui 源码 ，后续改造 二次开发，从哪里入手

**Comment by kensoh** [comment]
Hi @supercena,

This is TagUI architecture diagram - https://github.com/aisingapore/TagUI/tree/pre_v6?tab=readme-ov-file#automation-workflow

- The entry point are the files src/tagui.cmd (Windows) and src/tagui (macOS and Linux)
- When invoked, it will call src/tagui_parse.php to convert human language to JavaScript code
- The src/tagui_header.js has a lot of code for live mode and is the header file used by tagui_parse.php
- Exactly what to modify depends on what you want to enhance, basically TagUI generates a .js file and run it
