### ISSUE TITLE
Can we create a method for reuse across various places? - use tag and subflows

### ISSUE THREAD

**Issue by gauravgandhi1315** [aisingapore/TagUI#1373]

**Comment by marcelocecin** [comment]
https://github.com/aisingapore/TagUI/issues/938

**Comment by kensoh** [comment]
Thanks @marcelocecin ! Hi @gauravgandhi1315 also linking to the doc on this tag step - https://tagui.readthedocs.io/en/latest/advanced.html#running-flows-within-a-flow

It is also possible to write JavaScript functions to reused across TagUI, but I think in the documentation this part isn't mention, to cater more for business user vs hardcore developer.
