### ISSUE TITLE
请教下，现在有个需求就是要在当前已经打开的浏览器用tagui执行流程，非临时浏览器，有啥办法或者思路去实现吗？谢谢

### ISSUE THREAD

**Issue by 15295739756** [aisingapore/TagUI#1375]
请教下，现在有个需求就是要在当前已经打开的浏览器用tagui执行流程，非临时浏览器，有啥办法或者思路去实现吗？谢谢

**Comment by supercena** [comment]
这个不好弄 目测要改源码

**Comment by kensoh** [comment]
This can only be done by using visual automation and keyboard. Because any existing Chrome browser will not have backdoor open for TagUI to control it. Chrome must be launched with websocket port open to let apps control it.
