### ISSUE TITLE
How to use casper object in tagui script? - no use, check this for visual logs

### ISSUE THREAD

**Issue by supercena** [aisingapore/TagUI#1376]
https://www.baidu.com
js begin
casper.then(function() {
    this.mouse.move(400, 300);   // moves cursor over coordinates x=400; y=300
});
js finish
wait  1000

**Comment by supercena** [comment]
it  not works. the mouse not move.  how to debug?

**Comment by kensoh** [comment]
Hi @supercena the casper object is only used internally. For troubleshooting visual automation, mouse or keyboard, check the tagui\src\tagui.sikuli folder for the logs of the SikuliX engine, which will show the error. I'll close issue for now but do reply back if hit blocker.

**Comment by supercena** [comment]
thanks

**Comment by marcelocecin** [comment]
@supercena here is an example of using casper: https://github.com/aisingapore/TagUI/issues/939
