### ISSUE TITLE
present() vs exist()? - exist() will wait until timeout before returning false

### ISSUE THREAD

**Issue by supercena** [aisingapore/TagUI#1379]
difference between present() and exist()?

**Comment by eienkisu** [comment]
refer to https://tagui.readthedocs.io/en/latest/reference.html?highlight=present#present

_present()_

Same as [exist()](https://tagui.readthedocs.io/en/latest/reference.html?highlight=present#exist) except that it does not wait until the timeout and immediately returns true or false.
Note that the identifier is surrounded by quotes.
Can use [DOM](https://tagui.readthedocs.io/en/latest/main_concepts.html#dom), [XPath](https://tagui.readthedocs.io/en/latest/main_concepts.html#xpath), [Image](https://tagui.readthedocs.io/en/latest/main_concepts.html#image) identifiers.

Examples

_if present('//table')
  click button1_
