### ISSUE TITLE
How to open a list of url from csv - try https:// prefix with link.substring(8)

### ISSUE THREAD

**Issue by microSoftware** [aisingapore/TagUI#1381]
I have a list of url in batch.csv
urla;b
https://website.com/@user1;a
https://website.com/user2;a

I run the script tagui script.tag batch.csv

the problem is i don't know how to actually open the url 
i've tried :
```
urla => doesn't work
url urla => doesn't work
run `chrome-cli open --new-tab ${urla}` => doesn't work
open urla => doesn't work
visit urla => doesn't work
```

The doc say we can use any value from the csv. But in my case, the value is the url, and i have no idea how to actually open it.

**Comment by ard-yansyah** [comment]
hi @microSoftware 

```
load test.csv to rows
rows = rows.split('\n')
for n from 0 to rows.length-1
  col = rows[n].split(';')
  link = col[0].slice(8, col[0].length)
  https://`link`
```
must use the word https:// or http://

**Comment by kensoh** [comment]
Hi @microSoftware, adding on to @microSoftware solution, if you are using datatable csv, the solution will be something like below, which truncates away the https:// from your data and still having the https:// prefix in the step so that TagUI know that you are loading a URL in the variable.

```
https://`urla.substring(8)`
```
