### ISSUE TITLE
'php' 不是内部或外部命令，也不是可运行的程序 或批处理文件。- check this

### ISSUE THREAD

**Issue by aurorax-neo** [aisingapore/TagUI#1382]
![image](https://github.com/user-attachments/assets/fbfb5bb6-5b3f-4fa7-a2c6-2ddc1cec02b6)

**Comment by kensoh** [comment]
Hi @aurorax-neo can you share how do you download TagUI? Can you see if there is a tagui\src\php\php.exe file?

My guess is either some reason with environment that TagUI cannot find the php.exe file or maybe company policy or anti-virus blocking it.

**Comment by kensoh** [comment]
(closing issue for now, but will look out for your reply if any)
