### ISSUE TITLE
Cannot open tag file in Dropbox folder - try copying file locally, maybe no access

### ISSUE THREAD

**Issue by eienkisu** [aisingapore/TagUI#1384]
anyone has similar issues?

ERROR - cannot find D:\Dropbox\abc.tag
ERROR - automation aborted due to above

my folder is set to be available offline. command prompt has not issue finding the file, but tagui cannot find file.

this could be the issue? but i still don't know how to fix it. https://answers.microsoft.com/en-us/windows/forum/all/cmd-prompt-returns-the-system-cannot-find-the-file/e8957c9b-504c-49e9-b531-4f267a70b0ff

**Comment by eienkisu** [comment]
this could be the issue? but i still don't know how to fix it. https://answers.microsoft.com/en-us/windows/forum/all/cmd-prompt-returns-the-system-cannot-find-the-file/e8957c9b-504c-49e9-b531-4f267a70b0ff

**Comment by kensoh** [comment]
Hi @eienkisu try copying the file to your local desktop or some folder in C: - I suspect maybe the user in the command prompt has no write access to your Dropbox folder

**Comment by kensoh** [comment]
(closing issue for now, but will look out for your reply if any)
