### ISSUE TITLE
Some questions about iframe need to ask you - use this syntax for subframe

### ISSUE THREAD

**Issue by XiaoluoMax** [aisingapore/TagUI#1386]
![80B47FC8-3DA6-4E83-8695-CABFFF31310A](https://github.com/user-attachments/assets/8595ceff-b630-48de-8f20-6c29ef1ecf43)

![71F405F4-050A-4045-96F7-7EA7544A852B](https://github.com/user-attachments/assets/edfd76b4-7b9b-4dff-99e2-1c1942536d79)
Hello developers, some questions about iframe need to ask you
![2AB90700-CEB4-4F8F-A725-9D0407ECA8D3](https://github.com/user-attachments/assets/da6c6498-5a96-45db-82ca-bf946bfd1ec6)
Figure 3 is my run window command, stuck in the last sentence
![26073E17-F4F5-4541-AB10-2A2EA7DD6DD6](https://github.com/user-attachments/assets/24f30927-822d-4920-9562-def3a3f01e12)
Figure 4 is my code statement

**Comment by XiaoluoMax** [comment]
Figure 4 is my code statement and Figure 3 is my run window command, which is stuck in the last sentence. As you can see, I tried to operate RPA to click a button, but it was in the second iframe, so I could not select this element. Is there any good way?

**Comment by kensoh** [comment]
Hi @XiaoluoMax the syntax for subframe is this

```
frame [frame name] | [subframe name]
    steps
```
```
frame forwardFrame | mainiframe
    steps
```

More info at the docs - https://tagui.readthedocs.io/en/latest/reference.html#frame

**Comment by XiaoluoMax** [comment]
Hi developer, I have tried many times and still can't get me to successfully click on the button element in the iframe, is there any way to print which frame I am currently in
![Uploading 5EF1EA6F-8A3F-4752-87B3-14DA8688E492.png…]()

**Comment by XiaoluoMax** [comment]
![37F76703-432D-4E83-94C2-1729D1F8EDC4](https://github.com/user-attachments/assets/2dd55447-d5a2-4d53-b862-ba9bb334672e)

**Comment by XiaoluoMax** [comment]
These are some additional errors, although I don't know what he means




[tagui] INPUT - [62] {"id":62,"method":"Runtime.evaluate","params":{"expression":"var result_bounds = document.evaluate('(//frame|//iframe)[@name=\"mainiframe\" or @id=\"mainiframe\"]',mainframe_context,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).getBoundingClientRect(); var result_rect = {top: Math.round(result_bounds.top), left: Math.round(result_bounds.left), width: Math.round(result_bounds.width), height: Math.round(result_bounds.height)}; result_rect","returnByValue":true}} [tagui] OUTPUT - [62] {"id":62,"result":{"result":{"type":"object","subtype":"error","className":"TypeError","description":"TypeError: Cannot read properties of null (reading 'getBoundingClientRect')\n at <anonymous>:1:183","objectId":"7072152145493749342.7.4"},"exceptionDetails":{"exceptionId":1,"text":"Uncaught","lineNumber":0,"columnNumber":182,"scriptId":"136","exception":{"type":"object","subtype":"error","className":"TypeError","description":"TypeError: Cannot read properties of null (reading 'getBoundingClientRect')\n at <anonymous>:1:183","objectId":"7072152145493749342.7.5"}}}} 


[tagui] INPUT - [63] {"id":63,"method":"Runtime.evaluate","params":{"expression":"subframe_context = document.evaluate('(//frame|//iframe)[@name=\"mainiframe\" or @id=\"mainiframe\"]',mainframe_context,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).contentDocument"}} [tagui] OUTPUT - [63] {"id":63,"result":{"result":{"type":"object","subtype":"error","className":"TypeError","description":"TypeError: Cannot read properties of null (reading 'contentDocument')\n at <anonymous>:1:182","objectId":"7072152145493749342.7.6"},"exceptionDetails":{"exceptionId":2,"text":"Uncaught","lineNumber":0,"columnNumber":181,"scriptId":"137","exception":{"type":"object","subtype":"error","className":"TypeError","description":"TypeError: Cannot read properties of null (reading 'contentDocument')\n at <anonymous>:1:182","objectId":"7072152145493749342.7.7"}}}}

**Comment by kensoh** [comment]
Hi @XiaoluoMax from above it looks like the subframe cannot be found for some reason. Are you able to access and visit the URL directly for the subframe? If you can you can automate that directly. The URL is the one just below the mainframe line in your first screenshot.

Otherwise, is your website accessible to public so I can have a look? If accessible can you share your code that can show this error?

**Comment by XiaoluoMax** [comment]
Hello developer, due to some security issues, the website cannot be opened to the public, but I think it may be the problem of the new TAB page. Which one is right below the first screen shot you mentioned? Please help me point out. As you can see, I first searched the page I need to enter in the search bar (1) of the home page. Then click to enter the search results page (2), and the elements in operation (2) are needed, and the code screenshots are also the elements in leaf page (2). Do I need to use "popup "when switching?
![8BD5809B-A255-45E5-A3A8-D5444EF10D61](https://github.com/user-attachments/assets/1f9b783a-fcb7-4b0d-ae49-119c652d27c0)
![3E5628FF-835B-4287-9CCF-6EF9DAF3EA5B](https://github.com/user-attachments/assets/079b6da8-a3da-4da8-9ecb-307dd5e97c47)

**Comment by marcelocecin** [comment]
Hi, if your automation is web only, try using the https://www.automa.site

**Comment by XiaoluoMax** [comment]
Hello developers, my problem about iframe has been solved, now when I encounter to switch a new TAB page, the URL will change and there is no way to use "popup" to switch
![Uploading 3B9EB17E-339E-4D7F-BF53-60385D63D7A8.png…]()
![Uploading 44052FD1-4806-456C-B55F-F56CA69961B9.png…]()

**Comment by XiaoluoMax** [comment]
！[C1EBBD8D-38B1-4059-95B2-EC980BEA6457]（https://github.com/user-attachments/assets/fb685a43-9aab-4d5b-b71f-7e65fa72d745）
![D0479109-04E6-4EA7-AF41-6EE68A0C76F0](https://github.com/user-attachments/assets/094109f0-894c-4d61-8d65-72709ff701e6)

**Comment by XiaoluoMax** [comment]
![54B20873-3F41-49CF-B993-0B6FD279B2DD](https://github.com/user-attachments/assets/01ea9aab-337e-450e-aa21-a84c5ee2dab3)
![2F9BBFB6-CC3E-4313-9EAF-8B0A1A6E4240](https://github.com/user-attachments/assets/c32ced00-b776-4682-a0fe-3440de35ab5d)

**Comment by XiaoluoMax** [comment]
Hello developers, my problem about iframe has been solved, now when I encounter to switch a new TAB page, the URL will change and there is no way to use "popup" to switch
![8C9C0518-7441-4FF9-BF91-13D152481D45](https://github.com/user-attachments/assets/98cadc8a-0667-4f94-b193-6338a2e5ea68)
![B9A0E0DF-4861-4CD6-972B-827F2D19D9AC](https://github.com/user-attachments/assets/8af45701-4f48-4e8d-8669-b2cfc2eb7c32)

**Comment by kensoh** [comment]
Hi @XiaoluoMax wow, this is tricky. There are 2 ways you can explore.

First way is you just need a small part of URL. Will using below work? It might work if parent page does not have this below in its URL.

popup ifr?page

Second way is are you able to see or read the URL from parent page then visit that page directly instead of using frame?

**Comment by XiaoluoMax** [comment]
Hello developers, the first way does not work, the parent page into the child page ulr changes only variables, is there any way to open the page, get the number of time variables, because the digital variables of this website are year, month, day, hour and minute seconds, can only wait until the page opens to get the correct variable, Is there anything you can do about the second option

**Comment by XiaoluoMax** [comment]
开发人员你好，第一种方法不起作用，父页面进入子页面ulr只更改变量后面的“页面”，是否有任何方法可以在页面中打开，获取时间变量编号，因为本网站的数字变量是年、月、日、小时和分秒，只能等到页面打开才能得到正确的变量，你对第二个选项有什么办法吗！[9C135261-EC8F-4127-95C8-062FC76A8F18]（https://github.com/user-attachments/assets/efde2a6b-19e1-4b10-be83-dbb0484ef301）！[4A7AE67E-EA87-44C8-925B-DA4A5108D8FE]（https://github.com/user-attachments/assets/5ef35d6b-6a67-4c19-8a2d-5daeafcd11c9）
The ones that are all numbers are the subpages

**Comment by XiaoluoMax** [comment]
Developer hello, the first way does not work, the parent page into the child page ulr changes only the "page" behind the variable, is there any way can be opened in the page, get the time variable number, because the number variable of this website is year, month, day, hour and minute seconds, can only wait until the page opens to get the correct variable, Is there anything you can do about the second option
![80A28AD7-A6A5-4FF7-8E62-7F7B1CF50F8C](https://github.com/user-attachments/assets/85b5799b-0180-4605-9e81-f2b186e96842)

**Comment by XiaoluoMax** [comment]
Developer hello, the first way does not work, the parent page into the child page ulr changes only the "page" behind the variable, is there any way can be opened in the page, get the time variable number, because the number variable of this website is year, month, day, hour and minute seconds, can only wait until the page opens to get the correct variable, Is there anything you can do about the second option
![1D8C8C23-266C-45BC-8112-C4CDC81F4145](https://github.com/user-attachments/assets/d88f3e70-337b-4968-9ef7-8965b69d9481)
![CCC73A3E-F693-4084-AF25-D89036F6274F](https://github.com/user-attachments/assets/15fdf7da-0a59-4272-97c7-e4c2becc0d82)
The ones that are all numbers are the subpages

**Comment by kensoh** [comment]
It sounds like it can't be automated. If you use visual automation and keyboard() on the popup new tab would it work for your use case? Otherwise I suspect that this scenario is not doable with the tool.

One last thing you can try is after new tab opens up, you do something like below. This forces popup() to point at the new tab because the parent tab is now pointing to google.com and does not have the 'page=' string in the URL.

r.url('https://google.com')
r.popup('page=')

**Comment by XiaoluoMax** [comment]
I'm sorry I don't understand what you mean, but I think I can restore the situation I encountered. The "page" content of the second subpage is a variable. How should I switch from the first subpage to the second subpage
![84799C6B-9485-4F92-8EE2-8D7054B4A05E](https://github.com/user-attachments/assets/d73b100a-f8b0-4b0c-b626-a657096604cb)
![F600BD31-357F-445E-882D-0BBCCC5F8951](https://github.com/user-attachments/assets/5c345c1f-88c7-4379-9912-616d365102b8)
![BE2680CD-5030-4C9A-8692-C47848384F41](https://github.com/user-attachments/assets/8ae4757e-a3bb-4537-a32e-f5c3aa344819)

**Comment by kensoh** [comment]
Hi @XiaoluoMax what I mean is after new tab appears, try the following to see if you can you get access to the new tab - 

https://google.com
popup page=
other steps

**Comment by kensoh** [comment]
But if there is a new tab and another new tab with very similar URLs other than the page ID which is random, I don't think this tool can easily or possibly automate this scenario.

**Comment by kensoh** [comment]
(Closing issue for now but will look out for reply)
