### ISSUE TITLE
win11兼容 issue with clicking on coordinates - pending logs and details

### ISSUE THREAD

**Issue by yyb6666** [aisingapore/TagUI#1387]
click点击坐标的指令（只有坐标）  键盘按键指令      win11不会执行会一直卡在那一步  也不报错 @kensoh

**Comment by kensoh** [comment]
Hi @yyb6666 can you share the logs in this folder? tagui\src\tagui.sikuli

That function is done using SikuliX engine. We can see more from the logs what happen.

**Comment by yyb6666** [comment]
这个功能是基于SikuliX 引擎完成的吗    是click (300,400)这样的点击坐标的指令  我现在发现也不是win11会有问题  有些win10 的系统也一样  就是到这一步就卡在那 不会执行了   也不会报任何错误  我感觉可能是缺少某些系统文件的问题
[tagui.sikuli.zip](https://github.com/user-attachments/files/16726715/tagui.sikuli.zip)
这是我tagui\src\tagui.sikuli文件夹下的全部文件  我没有找到日志

**Comment by kensoh** [comment]
Hi @yyb6666 can you try download TagUI and unzip it again? If you are copying from 1 PC to another you will have missing SikuliX file.

It looks like for some reason the SikuliX engine did not run. Have you installed OpenJDK using the setup instructions? That is required for SikuliX to run.

**Comment by yyb6666** [comment]
我安装了 OpenJDK  我现在发现了问题所在
![image](https://github.com/user-attachments/assets/8014d13b-20c5-4e62-a905-c3a78e885a32)
就是我设置了这个语言勾选Beta版 就会导致点击坐标的指令没有作用 如果不设置这个就有作用   但不设置这个从excel里导出的数据会是乱码  @kensoh

**Comment by kensoh** [comment]
Hi @yyb6666 I see.. That looks like a tricky problem. Is above screenshot part of OpenJDK setup?

I don't understand how OpenJDK setting can affect Excel automation setting. It is strange.

Which OpenJDK version are you installing? Can you try installing the version from TagUI installation page?

https://tagui.readthedocs.io/en/latest/setup.html
https://corretto.aws/downloads/latest/amazon-corretto-8-x64-windows-jdk.msi

**Comment by kensoh** [comment]
Closing issue for now but will look out for reply
