### ISSUE TITLE
tagui 如何打开浏览器插件的管理页面 - try this to open Chrome extensions page

### ISSUE THREAD

**Issue by supercena** [aisingapore/TagUI#1389]
比如在chrome安装了一个插件，它的浏览器地址 chrome-extension://*******/options.html#nav=utils
我想使用tagui 对浏览器插件的管理页面做一些操作

tagui 无法打开这个地址 chrome-extension://*******/options.html#nav=utils

请问如何处理或者其他的处理方式？

**Comment by supercena** [comment]
好的 我测试一下 谢谢  @kensoh

**Comment by supercena** [comment]
clipboard('chrome-extension://******/options.html#nav=utils')
keyboard [ctrl]v
keyboard [enter]

that is ok. thks @kensoh

**Comment by kensoh** [comment]
Welcome @supercena let me know if you run into other issue, thanks for posting above solution code!
