### ISSUE TITLE
想用 TagUI 做一些桌面网游的游戏自动化的操作，有没有大佬们有这方面的经验或者资料啥的

### ISSUE THREAD

**Issue by supercena** [aisingapore/TagUI#1391]
如题。

**Comment by kensoh** [comment]
@supercena I think you can use visual automation and keyboard step to automate games. Using OCR might be possible too.

It really depends on what type of game and the logic required to determine whether you can automate. Give it a try!

**Comment by supercena** [comment]
我发现 ocr识别之后 坐标有偏移 不知道有没有好的解决方案

**Comment by kensoh** [comment]
Can you tell me more what you mean? If you use OCR to click or type, the mouse will move to the text before clicking or typing.
