### ISSUE TITLE
要怎样去操作 getElementsByTagName - use dom

### ISSUE THREAD

**Issue by wwwzi1** [aisingapore/TagUI#1392]
js begin
var ifm document. getElementsByTagName('iframe');
js finish
echo `ifm`

我现在是这么写的 但是好像是错误的

**Comment by kensoh** [comment]
Hi @wwwzi1 use do step - 

https://tagui.readthedocs.io/en/latest/reference.html#dom

**Comment by supercena** [comment]
dom  document.getElementsByTagName("iframe")[0]

**Comment by wwwzi1** [comment]
> dom document.getElementsByTagName("iframe")[0]



> Hi @wwwzi1 use do step -
> 
> https://tagui.readthedocs.io/en/latest/reference.html#dom

ok 谢谢

**Comment by wwwzi1** [comment]
> Hi @wwwzi1 use do step -
> 
> https://tagui.readthedocs.io/en/latest/reference.html#dom

但是 我要怎么拿返回值呢 直接打印 echo `dom_result` 这个变量吗 按照文档上的操作 我现在获取的都是 null
