### ISSUE TITLE
Launching TagUI with Edge browser - pending replication and more details

### ISSUE THREAD

**Issue by XiaoluoMax** [aisingapore/TagUI#1393]
I used the statement "tagui my_tagui.tag-edge "Why is it still coming out of Google Chrome?

**Comment by kensoh** [comment]
Can you type below and tell me what do you see?

```
tagui
```

Then
```
tagui my_tagui.tag -edge
```

It should launch as Edge browser. Is your OS Windows or Linux or macOS?
