### ISSUE TITLE
iframe 标签没有 id和name属性 frame方法要怎么操作

### ISSUE THREAD

**Issue by wwwzi1** [aisingapore/TagUI#1394]
iframe 标签没有 id和name属性 frame方法要怎么操作

**Comment by supercena** [comment]
设置一个属性

**Comment by wwwzi1** [comment]
> 设置一个属性
@supercena 

dom 要怎么使用呀 我现在是这么写的 :
dom return docunmen.getElementsbytagname('iframe') 
echo `dom_result`
现在打印出来的是null

**Comment by wwwzi1** [comment]
> 设置一个属性

可以加一个你的联系方式吗 wx 或者 ins 想请教你一下

**Comment by supercena** [comment]
仿照下面写：

dom  document.getElementsByTagName("iframe")[0].setAttribute("name","自定义name")

frame  自定义name
{
    some code ......
}

**Comment by kensoh** [comment]
以上是理想答案。
