### ISSUE TITLE
frame 可以嵌套多少 iframe标 - only 2

### ISSUE THREAD

**Issue by wwwzi1** [aisingapore/TagUI#1395]
frame frm
    frame wkfrm
       frame detail
         frame ckw 
我现在只能找到第二个frame下面的元素 ， 后面两个的元素就获取不到了
我这个网页 的iframe 就像上边我写的那样 一层一层嵌套的

**Comment by kensoh** [comment]
Hi @wwwzi1 I'm afraid this can't be supported. The tool is designed only for 1st frame and 2nd frame. If you can get the URL of the frame content you can try accessing it directly instead of going through frame step.

**Comment by supercena** [comment]
你的网址能发出来？瞅一眼

**Comment by kensoh** [comment]
My website? tebel.org

I have a python version of TagUI called RPA for Python. LinkedIn is Ken Soh
