### ISSUE TITLE
Cannot download TagUI on macbook - see this guide and this step

### ISSUE THREAD

**Issue by littlevinecreations** [aisingapore/TagUI#1396]
i have followed instructions until the terminal step. when i copied and paste the commands, the output on the terminal says this:

ln: /usr/local/bin/tagui: No such file or directory
zsh: command not found: tagui 

i am already using google chrome and my unzip files are on my desktop. i have also installed openJDK.

appreciate advice! thanks!

**Comment by kensoh** [comment]
https://tagui.readthedocs.io/en/latest/setup.html
sudo ln -sf /your_tagui_path/tagui/src/tagui /usr/local/bin/tagui

Hi @littlevinecreations from your error message it sounds like above step in installation instructions is not yet completed.
