### ISSUE TITLE
I need to read and write Excel, I have been unable to complete - see this

### ISSUE THREAD

**Issue by XiaoluoMax** [aisingapore/TagUI#1397]
The image is my code

**Comment by XiaoluoMax** [comment]
![1493FC19-FDD9-4E77-9119-5C0F4F47BB1C](https://github.com/user-attachments/assets/5b0faadc-e6e9-48c8-ac83-775f44c3515a)
![77018FF3-2AB3-4538-83E4-226FF6513694](https://github.com/user-attachments/assets/5504167a-7f9d-4a33-99e5-bea29b2b16c4)
![AB6F4929-0EC6-42E1-A958-114107CEACA1](https://github.com/user-attachments/assets/b2bc3d88-fffc-4760-9765-56ab0799f968)

**Comment by supercena** [comment]
https://tagui.readthedocs.io/en/latest/reference.html#excel

**Comment by XiaoluoMax** [comment]
> 网址https://tagui.readthedocs.io/en/latest/reference.html#excel

我写的有问题是吗

**Comment by kensoh** [comment]
@XiaoluoMax for datatables, you need to have headers, see this - https://tagui.readthedocs.io/en/latest/advanced.html#datatables-for-batch-automation

But if you are trying to read from Excel, there is no need to specify t.xlsx in your tagui command.
