### ISSUE TITLE
ERROR -31 is not a constructor (evaluting 'count('XPath')') - try this 

### ISSUE THREAD

**Issue by wwwzi1** [aisingapore/TagUI#1399]
count = count("XPath")
for i from 1 to page
    for n from 1 to count
       if (n = count )
          click nextPage
          count = count('XPath')
重复获取相同特征元素数量 会报错 ,不是构造参数

ERROR -31 is not a constructor (evaluting 'count('XPath')')

**Comment by kensoh** [comment]
You can try below to avoid using variable name to be the same as function name count. But I don't think you can change the for loop total while it has entered the loop, you can think of other ways to achieve what you want.

```
total = count("XPath")
for i from 1 to page
    for n from 1 to total
       if n equals to total
          click nextPage
          wait
          total = count('XPath')
```
