### ISSUE TITLE
src\chrome目录的 tagui_user_profile 这个可以替换成我本地？- 是的

### ISSUE THREAD

**Issue by supercena** [aisingapore/TagUI#1401]
比如我本地电脑的chrome 浏览器有自己的用户目录,里面有一些插件的相关配置，我直接覆盖源码tagui_user_profile 这个目录,是否ok? 还是说有一些特殊设置

**Comment by supercena** [comment]
我发现源码里面 有一行 start "" "!chrome_command!" --user-data-dir="%~dp0chrome\tagui_user_profile" !chrome_switches! !window_size! !headless_switch! !no_sandbox_switch!  。我用我的user-data-dir 替换了覆盖了tagui_user_profile源码，可以跑起来。

**Comment by kensoh** [comment]
Correct yes you found it! That folder stores the automation user and states of logged in websites. Let me know if you have other questions.

**Comment by supercena** [comment]
@kensoh thanks
