### ISSUE TITLE
如何移动鼠标到浏览器地址栏并且是选中的状态？- 试试这个

### ISSUE THREAD

**Issue by supercena** [aisingapore/TagUI#1403]
比如我的鼠标在浏览器窗口之外，使用键盘指令操作浏览器地址栏无效，我想把鼠标移动到浏览器地址栏，并且选中地址栏。使用orc?还是有其他方案?

**Comment by kensoh** [comment]
Hi @supercena you can try to use visual automation to click on web browser icon on task bar. Then use keyboard step to do keyboard shortcut to go to address bar of browser.

**Comment by supercena** [comment]
ok  thanks
