### ISSUE TITLE
js begin代码中最后返回的数据 我要如何在js之外拿到 - see this

### ISSUE THREAD

**Issue by wwwzi1** [aisingapore/TagUI#1406]
js begin
   content = document.documentElement.testContent;
    obj = json.parse(content)
js finish

echo `obj`

类似这种 我要怎么在外边拿到这个 obj

**Comment by kensoh** [comment]
Hi @wwwzi1 do you want to read info from the DOM of the webpage?

If yes, you have to use dom step. Using above is just the JavaScript engine in TagUI, which is different from the JavaScript in Chrome browser debugger window.

See this examples here - https://tagui.readthedocs.io/en/latest/reference.html#dom

**Comment by wwwzi1** [comment]
> 你好@wwwzi1您想从网页的 DOM 中读取信息吗？
> 
> 如果是，那么就必须使用 dom 步骤。上面使用的只是 TagUI 中的 JavaScript 引擎，与 Chrome 浏览器调试器窗口中的 JavaScript 不同。
> 
> 请参阅此处的示例 - https://tagui.readthedocs.io/en/latest/reference.html#dom

不是的 是我使用js调用我们系统接口最后返回的接口数据

**Comment by kensoh** [comment]
If that's the case then the obj is already usable. But I don't think you can echo an object directly. You probably can do obj.element.element.element etc to the value.
