### ISSUE TITLE
执行完 jsbegin中的代码之后无法正常运行 tagui - 查这里的代码

### ISSUE THREAD

**Issue by wwwzi1** [aisingapore/TagUI#1407]
js begin
var page  = require('webpage').create();
var fs =  require('fs');
'''''''
'''''''
'''''''
phantom.exit();
js finish

for n from 1 to 10 
  echo n

n只能 循环到2 就结束了

**Comment by kensoh** [comment]
Why do you do phantom.exit()?

It will kill TagUI because TagUI runs on it.
