### ISSUE TITLE
tagui 有没有那种画中画的功能 - no plan for picture-in-picture 

### ISSUE THREAD

**Issue by supercena** [aisingapore/TagUI#1410]
市面上rpa 有画中画的功能，咱们的tagui啥时候支持?或者有其他方式实现？

**Comment by kensoh** [comment]
没有 picture-in-picture 的功能
可能你需要用VM。

If your are just doing web automation on Chrome, I think you can continue to use the computer while RPA is automating Chrome.

**Comment by supercena** [comment]
ok 了解
