### ISSUE TITLE
keyboard [pagedown] does not work on webpage - set focus on the web page first

### ISSUE THREAD

**Issue by jolo26** [aisingapore/TagUI#1413]
When I use page keyboard [pagedown] command, it does not perform the pagedown on the webpage. What it does is it goes to the address bar, it will then perform the pagedown function. I think this is a bug or maybe Im using it wrong? hope someone will notice this and give comments.

**Comment by kensoh** [comment]
You need to use visual automation to click onto the page or some web element on the page first. Then use keyboard step. Otherwise the focus is not yet on the webpage and page down is sent to the wrong place.

**Comment by kensoh** [comment]
For eg clicking something on the web page to set focus to the web page
click button.png

**Comment by jolo26** [comment]
@kensoh thank you. it worked. Just to share additional details, when I click web elements using click <xpath>, the page is still not active but when I use click <coordinates>, the page becomes active and the keyboard function works after that.
