### ISSUE TITLE
Captcha question - try captcha solving services with api step

### ISSUE THREAD

**Issue by XiaoluoMax** [aisingapore/TagUI#1415]
Login when encountered graphic verification code need to solve, trouble for a long time
![F61DE2A3-E322-400F-AC7E-287F3BA1C462](https://github.com/user-attachments/assets/5eee622b-9736-4109-8130-cb81ea07a5a2)

**Comment by kensoh** [comment]
Hi @XiaoluoMax try using captcha solving services like below and combine with api step
https://2captcha.com/
https://www.capsolver.com/

**Comment by sanikommurakeesh** [comment]
any open source captcha are there to solve

**Comment by kensoh** [comment]
Oh I don't think there will be because there will be costs and human workers as backups.
