### ISSUE TITLE
keyboard command not working - try reinstalling or check the logs here

### ISSUE THREAD

**Issue by sanikommurakeesh** [aisingapore/TagUI#1419]
i have tried run keyboard commands on my mac those are not working in my laptop i have given all permissions for vs code still those are not working can some one fix my issuse ?     thanks in advance

**Comment by kensoh** [comment]
Hi @sanikommurakeesh is Java installed? OpenJDK 8 minimum or Java 8 minimum is needed. You can try following the setup instructions again here to see if it helps. https://tagui.readthedocs.io/en/latest/setup.html#macos-linux

Also, can you check what is in the logs in tagui/src/tagui.sikuli folder?

**Comment by 15634130221** [comment]
![1735285008381](https://github.com/user-attachments/assets/5a914fcb-decf-4a63-9851-1decb35832a1)
麻烦请问， 这种情况是什么原因造成的？感谢

**Comment by kensoh** [comment]
Oh can't find python. I think it's because python 3 command is python3 not python. You look for this file tagui/src/tagui and edit it. Replace the python command with python3

**Comment by 15634130221** [comment]
> 哦，找不到python。我认为这是因为python 3命令是python3而不是python。你找到这个文件tagui/src/tagui并编辑它。将python命令替换为python3

感谢您， 这个问题已经解决， 还有一个问题想咨询一下您， 是关于定位命令 ， 如果定位命令的参数使用的是img的情况下是否需要安装visual automation？如果需要能否提供一下文档或者程序地址？

**Comment by 15634130221** [comment]
> Oh can't find python. I think it's because python 3 command is python3 not python. You look for this file tagui/src/tagui and edit it. Replace the python command with python3

十分感谢您
