### ISSUE TITLE
-n 模式 无法找到地址

### ISSUE THREAD

**Issue by wincol1151** [aisingapore/TagUI#1420]
我有发现一个问题 我在编写好一个tag 脚本后 如果使用 -n 模式 在点击某个固定地址的时候 总是显示无法找到地址 但是如果不使用-n 模式去可以找到并点击成功   我的谷歌浏览器版本 127.0.6533.73   tagui版本 6.110   这个问题 一般会出在哪里呢

**Comment by kensoh** [comment]
@wincol1151 -n is to launch TagUI without Chrome browser but only use the legacy PhantomJS browser. It is an old browser which does not work with many websites. You can try -h to run with headless Chrome to see if that solves for your scenario.

**Comment by wincol1151** [comment]
太感谢了 可能是我的这个网站的问题   如果用-h 也会有的地方找不到地址  不过 没关系  还是可以用-t 的形式 加速 就行了
