### ISSUE TITLE
How to use Sikuli to identify and click on the picture - see these

### ISSUE THREAD

**Issue by 15634130221** [aisingapore/TagUI#1421]
Hello, how to use Sikuli? I have downloaded the jar package, and run it, and then through the tagui command, run the double click desktop image command and the resolution command 0.5 command, the desktop image still does not react.
I am researching tagui how to use visual automation function，hoping to get an answer。
![1735543163938](https://github.com/user-attachments/assets/662bcbdc-13bf-4ed8-9298-8d15ed62a7df)

**Comment by 15634130221** [comment]
> Hello, how to use Sikuli? I have downloaded the jar package, and run it, and then through the tagui command, run the double click desktop image command and the resolution command 0.5 command, the desktop image still does not react. I am researching tagui how to use visual automation function，hoping to get an answer。
![1735542783946](https://github.com/user-attachments/assets/836b5154-1e79-404f-bc9e-69ecaf831181)

**Comment by kensoh** [comment]
Hi @15634130221 install TagUI using these steps no need to install SikuliX yourself.

https://tagui.readthedocs.io/en/latest/setup.html

You can use visual automation directly with click button.png and so on
https://tagui.readthedocs.io/en/latest/main_concepts.html#click

**Comment by 15634130221** [comment]
> Hi @15634130221 install TagUI using these steps no need to install SikuliX yourself.
> 
> https://tagui.readthedocs.io/en/latest/setup.html
> 
> You can use visual automation directly with click button.png and so on https://tagui.readthedocs.io/en/latest/main_concepts.html#click

Thank you very much for your reply. I have solved this problem
